/* soapH.h
   Generated by gSOAP 2.7.12 from D:\program\huaWei\soap1\soap\huaWei.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef SOAP_TYPE__ns1__ValueChangeResponse
#define SOAP_TYPE__ns1__ValueChangeResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ValueChangeResponse(struct soap*, const char*, int, const _ns1__ValueChangeResponse *, const char*);
SOAP_FMAC3 _ns1__ValueChangeResponse * SOAP_FMAC4 soap_get__ns1__ValueChangeResponse(struct soap*, _ns1__ValueChangeResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__ValueChangeResponse * SOAP_FMAC4 soap_in__ns1__ValueChangeResponse(struct soap*, const char*, _ns1__ValueChangeResponse *, const char*);
SOAP_FMAC5 _ns1__ValueChangeResponse * SOAP_FMAC6 soap_new__ns1__ValueChangeResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__ValueChangeResponse(struct soap*, _ns1__ValueChangeResponse*);
SOAP_FMAC3 _ns1__ValueChangeResponse * SOAP_FMAC4 soap_instantiate__ns1__ValueChangeResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ValueChangeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__ValueChange
#define SOAP_TYPE__ns1__ValueChange (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ValueChange(struct soap*, const char*, int, const _ns1__ValueChange *, const char*);
SOAP_FMAC3 _ns1__ValueChange * SOAP_FMAC4 soap_get__ns1__ValueChange(struct soap*, _ns1__ValueChange *, const char*, const char*);
SOAP_FMAC3 _ns1__ValueChange * SOAP_FMAC4 soap_in__ns1__ValueChange(struct soap*, const char*, _ns1__ValueChange *, const char*);
SOAP_FMAC5 _ns1__ValueChange * SOAP_FMAC6 soap_new__ns1__ValueChange(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__ValueChange(struct soap*, _ns1__ValueChange*);
SOAP_FMAC3 _ns1__ValueChange * SOAP_FMAC4 soap_instantiate__ns1__ValueChange(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ValueChange(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__BootResponse
#define SOAP_TYPE__ns1__BootResponse (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__BootResponse(struct soap*, const char*, int, const _ns1__BootResponse *, const char*);
SOAP_FMAC3 _ns1__BootResponse * SOAP_FMAC4 soap_get__ns1__BootResponse(struct soap*, _ns1__BootResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__BootResponse * SOAP_FMAC4 soap_in__ns1__BootResponse(struct soap*, const char*, _ns1__BootResponse *, const char*);
SOAP_FMAC5 _ns1__BootResponse * SOAP_FMAC6 soap_new__ns1__BootResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__BootResponse(struct soap*, _ns1__BootResponse*);
SOAP_FMAC3 _ns1__BootResponse * SOAP_FMAC4 soap_instantiate__ns1__BootResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__BootResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Boot
#define SOAP_TYPE__ns1__Boot (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Boot(struct soap*, const char*, int, const _ns1__Boot *, const char*);
SOAP_FMAC3 _ns1__Boot * SOAP_FMAC4 soap_get__ns1__Boot(struct soap*, _ns1__Boot *, const char*, const char*);
SOAP_FMAC3 _ns1__Boot * SOAP_FMAC4 soap_in__ns1__Boot(struct soap*, const char*, _ns1__Boot *, const char*);
SOAP_FMAC5 _ns1__Boot * SOAP_FMAC6 soap_new__ns1__Boot(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__Boot(struct soap*, _ns1__Boot*);
SOAP_FMAC3 _ns1__Boot * SOAP_FMAC4 soap_instantiate__ns1__Boot(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Boot(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ParameterValueStruct
#define SOAP_TYPE_ns1__ParameterValueStruct (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ParameterValueStruct(struct soap*, const char*, int, const ns1__ParameterValueStruct *, const char*);
SOAP_FMAC3 ns1__ParameterValueStruct * SOAP_FMAC4 soap_get_ns1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct *, const char*, const char*);
SOAP_FMAC3 ns1__ParameterValueStruct * SOAP_FMAC4 soap_in_ns1__ParameterValueStruct(struct soap*, const char*, ns1__ParameterValueStruct *, const char*);
SOAP_FMAC5 ns1__ParameterValueStruct * SOAP_FMAC6 soap_new_ns1__ParameterValueStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct*);
SOAP_FMAC3 ns1__ParameterValueStruct * SOAP_FMAC4 soap_instantiate_ns1__ParameterValueStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ParameterValueStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (11)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterValueList(struct soap*, const char*, int, const ParameterValueList *, const char*);
SOAP_FMAC3 ParameterValueList * SOAP_FMAC4 soap_get_ParameterValueList(struct soap*, ParameterValueList *, const char*, const char*);
SOAP_FMAC3 ParameterValueList * SOAP_FMAC4 soap_in_ParameterValueList(struct soap*, const char*, ParameterValueList *, const char*);
SOAP_FMAC5 ParameterValueList * SOAP_FMAC6 soap_new_ParameterValueList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ParameterValueList(struct soap*, ParameterValueList*);
SOAP_FMAC3 ParameterValueList * SOAP_FMAC4 soap_instantiate_ParameterValueList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ParameterValueList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__DeviceIdStruct
#define SOAP_TYPE_ns1__DeviceIdStruct (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DeviceIdStruct(struct soap*, const char*, int, const ns1__DeviceIdStruct *, const char*);
SOAP_FMAC3 ns1__DeviceIdStruct * SOAP_FMAC4 soap_get_ns1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct *, const char*, const char*);
SOAP_FMAC3 ns1__DeviceIdStruct * SOAP_FMAC4 soap_in_ns1__DeviceIdStruct(struct soap*, const char*, ns1__DeviceIdStruct *, const char*);
SOAP_FMAC5 ns1__DeviceIdStruct * SOAP_FMAC6 soap_new_ns1__DeviceIdStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct*);
SOAP_FMAC3 ns1__DeviceIdStruct * SOAP_FMAC4 soap_instantiate_ns1__DeviceIdStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__DeviceIdStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anySimpleType(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anySimpleType(struct soap*, std::string const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anySimpleType(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anySimpleType(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__anySimpleType(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__anySimpleType(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_xsd__anySimpleType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anySimpleType(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_xsd__anySimpleType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anySimpleType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__ValueChange
#define SOAP_TYPE___ns1__ValueChange (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__ValueChange(struct soap*, struct __ns1__ValueChange *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__ValueChange(struct soap*, const struct __ns1__ValueChange *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__ValueChange(struct soap*, const struct __ns1__ValueChange *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__ValueChange(struct soap*, const char*, int, const struct __ns1__ValueChange *, const char*);
SOAP_FMAC3 struct __ns1__ValueChange * SOAP_FMAC4 soap_get___ns1__ValueChange(struct soap*, struct __ns1__ValueChange *, const char*, const char*);
SOAP_FMAC3 struct __ns1__ValueChange * SOAP_FMAC4 soap_in___ns1__ValueChange(struct soap*, const char*, struct __ns1__ValueChange *, const char*);
SOAP_FMAC5 struct __ns1__ValueChange * SOAP_FMAC6 soap_new___ns1__ValueChange(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__ValueChange(struct soap*, struct __ns1__ValueChange*);
SOAP_FMAC3 struct __ns1__ValueChange * SOAP_FMAC4 soap_instantiate___ns1__ValueChange(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__ValueChange(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__Boot
#define SOAP_TYPE___ns1__Boot (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Boot(struct soap*, struct __ns1__Boot *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Boot(struct soap*, const struct __ns1__Boot *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Boot(struct soap*, const struct __ns1__Boot *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Boot(struct soap*, const char*, int, const struct __ns1__Boot *, const char*);
SOAP_FMAC3 struct __ns1__Boot * SOAP_FMAC4 soap_get___ns1__Boot(struct soap*, struct __ns1__Boot *, const char*, const char*);
SOAP_FMAC3 struct __ns1__Boot * SOAP_FMAC4 soap_in___ns1__Boot(struct soap*, const char*, struct __ns1__Boot *, const char*);
SOAP_FMAC5 struct __ns1__Boot * SOAP_FMAC6 soap_new___ns1__Boot(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__Boot(struct soap*, struct __ns1__Boot*);
SOAP_FMAC3 struct __ns1__Boot * SOAP_FMAC4 soap_instantiate___ns1__Boot(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Boot(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__ValueChangeResponse
#define SOAP_TYPE_PointerTo_ns1__ValueChangeResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ValueChangeResponse(struct soap*, _ns1__ValueChangeResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ValueChangeResponse(struct soap*, _ns1__ValueChangeResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ValueChangeResponse(struct soap*, const char *, int, _ns1__ValueChangeResponse *const*, const char *);
SOAP_FMAC3 _ns1__ValueChangeResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__ValueChangeResponse(struct soap*, _ns1__ValueChangeResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__ValueChangeResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__ValueChangeResponse(struct soap*, const char*, _ns1__ValueChangeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ValueChange
#define SOAP_TYPE_PointerTo_ns1__ValueChange (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ValueChange(struct soap*, _ns1__ValueChange *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ValueChange(struct soap*, _ns1__ValueChange *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ValueChange(struct soap*, const char *, int, _ns1__ValueChange *const*, const char *);
SOAP_FMAC3 _ns1__ValueChange ** SOAP_FMAC4 soap_get_PointerTo_ns1__ValueChange(struct soap*, _ns1__ValueChange **, const char*, const char*);
SOAP_FMAC3 _ns1__ValueChange ** SOAP_FMAC4 soap_in_PointerTo_ns1__ValueChange(struct soap*, const char*, _ns1__ValueChange **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__BootResponse
#define SOAP_TYPE_PointerTo_ns1__BootResponse (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__BootResponse(struct soap*, _ns1__BootResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__BootResponse(struct soap*, _ns1__BootResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__BootResponse(struct soap*, const char *, int, _ns1__BootResponse *const*, const char *);
SOAP_FMAC3 _ns1__BootResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__BootResponse(struct soap*, _ns1__BootResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__BootResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__BootResponse(struct soap*, const char*, _ns1__BootResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__Boot
#define SOAP_TYPE_PointerTo_ns1__Boot (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Boot(struct soap*, _ns1__Boot *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Boot(struct soap*, _ns1__Boot *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Boot(struct soap*, const char *, int, _ns1__Boot *const*, const char *);
SOAP_FMAC3 _ns1__Boot ** SOAP_FMAC4 soap_get_PointerTo_ns1__Boot(struct soap*, _ns1__Boot **, const char*, const char*);
SOAP_FMAC3 _ns1__Boot ** SOAP_FMAC4 soap_in_PointerTo_ns1__Boot(struct soap*, const char*, _ns1__Boot **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__ParameterValueStruct
#define SOAP_TYPE_PointerToPointerTons1__ParameterValueStruct (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__ParameterValueStruct(struct soap*, const char *, int, ns1__ParameterValueStruct **const*, const char *);
SOAP_FMAC3 ns1__ParameterValueStruct *** SOAP_FMAC4 soap_get_PointerToPointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct ***, const char*, const char*);
SOAP_FMAC3 ns1__ParameterValueStruct *** SOAP_FMAC4 soap_in_PointerToPointerTons1__ParameterValueStruct(struct soap*, const char*, ns1__ParameterValueStruct ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__ParameterValueStruct
#define SOAP_TYPE_PointerTons1__ParameterValueStruct (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ParameterValueStruct(struct soap*, const char *, int, ns1__ParameterValueStruct *const*, const char *);
SOAP_FMAC3 ns1__ParameterValueStruct ** SOAP_FMAC4 soap_get_PointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct **, const char*, const char*);
SOAP_FMAC3 ns1__ParameterValueStruct ** SOAP_FMAC4 soap_in_PointerTons1__ParameterValueStruct(struct soap*, const char*, ns1__ParameterValueStruct **, const char*);

#ifndef SOAP_TYPE_PointerToParameterValueList
#define SOAP_TYPE_PointerToParameterValueList (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterValueList(struct soap*, ParameterValueList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterValueList(struct soap*, ParameterValueList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterValueList(struct soap*, const char *, int, ParameterValueList *const*, const char *);
SOAP_FMAC3 ParameterValueList ** SOAP_FMAC4 soap_get_PointerToParameterValueList(struct soap*, ParameterValueList **, const char*, const char*);
SOAP_FMAC3 ParameterValueList ** SOAP_FMAC4 soap_in_PointerToParameterValueList(struct soap*, const char*, ParameterValueList **, const char*);

#ifndef SOAP_TYPE_PointerTons1__DeviceIdStruct
#define SOAP_TYPE_PointerTons1__DeviceIdStruct (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DeviceIdStruct(struct soap*, const char *, int, ns1__DeviceIdStruct *const*, const char *);
SOAP_FMAC3 ns1__DeviceIdStruct ** SOAP_FMAC4 soap_get_PointerTons1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct **, const char*, const char*);
SOAP_FMAC3 ns1__DeviceIdStruct ** SOAP_FMAC4 soap_in_PointerTons1__DeviceIdStruct(struct soap*, const char*, ns1__DeviceIdStruct **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
