/* soapcwmpProxy.h
   Generated by gSOAP 2.7.12 from D:\program\huaWei\soap1\soap\huaWei.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapcwmpProxy_H
#define soapcwmpProxy_H
#include "soapH.h"
class cwmp
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'cwmp' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	cwmp()
	{ soap = soap_new(); endpoint = "http://localhost:8080/cwmp"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "urn:dslforum-org:cwmp-1-1", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~cwmp() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'Boot' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __ns1__Boot(_ns1__Boot *ns1__Boot, _ns1__BootResponse *ns1__BootResponse) { return soap ? soap_call___ns1__Boot(soap, endpoint, NULL, ns1__Boot, ns1__BootResponse) : SOAP_EOM; };
	/// Invoke 'ValueChange' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __ns1__ValueChange(_ns1__ValueChange *ns1__ValueChange, _ns1__ValueChangeResponse *ns1__ValueChangeResponse) { return soap ? soap_call___ns1__ValueChange(soap, endpoint, NULL, ns1__ValueChange, ns1__ValueChangeResponse) : SOAP_EOM; };
};
#endif
