/* soapDcmPortBindingProxy.h
   Generated by gSOAP 2.7.12 from dcm.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapDcmPortBindingProxy_H
#define soapDcmPortBindingProxy_H
#include "soapH.h"
class DcmPortBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'DcmPortBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	char strTemp[1024];

	DcmPortBinding()
	{ soap = soap_new(); endpoint = "http://192.168.0.56:8688/DCMService/services/Dcm.DcmPort/"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://wsdl.intf.dcm.intel.com/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };

	DcmPortBinding(std::string strWeb, int nPort)
	{ 
		soap = soap_new();
		sprintf(strTemp,"http://%s:%d/DCMService/services/Dcm.DcmPort/",strWeb.c_str(), nPort);
		endpoint = strTemp;
//		endpoint = "http://192.168.0.56:8688/DCMService/services/Dcm.DcmPort/"; 
		
		if (soap && !soap->namespaces) 
		{
			static const struct Namespace namespaces[] = 
			{
				{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
				{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
				{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
				{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
				{"ns1", "http://wsdl.intf.dcm.intel.com/", NULL, NULL},
				{NULL, NULL, NULL, NULL}
			};
			soap->namespaces = namespaces;
		} 
	};
	/// Destructor frees deserialized data and soap engine context
	virtual ~DcmPortBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'getVersion' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getVersion(ns1__getVersion *ns1__getVersion_, ns1__getVersionResponse *ns1__getVersionResponse_) { return soap ? soap_call___ns1__getVersion(soap, endpoint, NULL, ns1__getVersion_, ns1__getVersionResponse_) : SOAP_EOM; };
	/// Invoke 'setPolicy' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setPolicy(ns1__setPolicy *ns1__setPolicy_, ns1__setPolicyResponse *ns1__setPolicyResponse_) { return soap ? soap_call___ns1__setPolicy(soap, endpoint, NULL, ns1__setPolicy_, ns1__setPolicyResponse_) : SOAP_EOM; };
	/// Invoke 'updatePolicy' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__updatePolicy(ns1__updatePolicy *ns1__updatePolicy_, ns1__updatePolicyResponse *ns1__updatePolicyResponse_) { return soap ? soap_call___ns1__updatePolicy(soap, endpoint, NULL, ns1__updatePolicy_, ns1__updatePolicyResponse_) : SOAP_EOM; };
	/// Invoke 'addEntity' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__addEntity(ns1__addEntity *ns1__addEntity_, ns1__addEntityResponse *ns1__addEntityResponse_) { return soap ? soap_call___ns1__addEntity(soap, endpoint, NULL, ns1__addEntity_, ns1__addEntityResponse_) : SOAP_EOM; };
	/// Invoke 'associateEntity' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__associateEntity(ns1__associateEntity *ns1__associateEntity_, ns1__associateEntityResponse *ns1__associateEntityResponse_) { return soap ? soap_call___ns1__associateEntity(soap, endpoint, NULL, ns1__associateEntity_, ns1__associateEntityResponse_) : SOAP_EOM; };
	/// Invoke 'defineCustomEvent' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__defineCustomEvent(ns1__defineCustomEvent *ns1__defineCustomEvent_, ns1__defineCustomEventResponse *ns1__defineCustomEventResponse_) { return soap ? soap_call___ns1__defineCustomEvent(soap, endpoint, NULL, ns1__defineCustomEvent_, ns1__defineCustomEventResponse_) : SOAP_EOM; };
	/// Invoke 'deleteSecretKey' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__deleteSecretKey(ns1__deleteSecretKey *ns1__deleteSecretKey_, ns1__deleteSecretKeyResponse *ns1__deleteSecretKeyResponse_) { return soap ? soap_call___ns1__deleteSecretKey(soap, endpoint, NULL, ns1__deleteSecretKey_, ns1__deleteSecretKeyResponse_) : SOAP_EOM; };
	/// Invoke 'disassociateEntity' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__disassociateEntity(ns1__disassociateEntity *ns1__disassociateEntity_, ns1__disassociateEntityResponse *ns1__disassociateEntityResponse_) { return soap ? soap_call___ns1__disassociateEntity(soap, endpoint, NULL, ns1__disassociateEntity_, ns1__disassociateEntityResponse_) : SOAP_EOM; };
	/// Invoke 'enumerateCustomEvents' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__enumerateCustomEvents(ns1__enumerateCustomEvents *ns1__enumerateCustomEvents_, ns1__enumerateCustomEventsResponse *ns1__enumerateCustomEventsResponse_) { return soap ? soap_call___ns1__enumerateCustomEvents(soap, endpoint, NULL, ns1__enumerateCustomEvents_, ns1__enumerateCustomEventsResponse_) : SOAP_EOM; };
	/// Invoke 'enumerateEntities' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__enumerateEntities(ns1__enumerateEntities *ns1__enumerateEntities_, ns1__enumerateEntitiesResponse *ns1__enumerateEntitiesResponse_) { return soap ? soap_call___ns1__enumerateEntities(soap, endpoint, NULL, ns1__enumerateEntities_, ns1__enumerateEntitiesResponse_) : SOAP_EOM; };
	/// Invoke 'enumerateEventHandlers' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__enumerateEventHandlers(ns1__enumerateEventHandlers *ns1__enumerateEventHandlers_, ns1__enumerateEventHandlersResponse *ns1__enumerateEventHandlersResponse_) { return soap ? soap_call___ns1__enumerateEventHandlers(soap, endpoint, NULL, ns1__enumerateEventHandlers_, ns1__enumerateEventHandlersResponse_) : SOAP_EOM; };
	/// Invoke 'enumeratePolicies' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__enumeratePolicies(ns1__enumeratePolicies *ns1__enumeratePolicies_, ns1__enumeratePoliciesResponse *ns1__enumeratePoliciesResponse_) { return soap ? soap_call___ns1__enumeratePolicies(soap, endpoint, NULL, ns1__enumeratePolicies_, ns1__enumeratePoliciesResponse_) : SOAP_EOM; };
	/// Invoke 'exportHierarchy' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__exportHierarchy(ns1__exportHierarchy *ns1__exportHierarchy_, ns1__exportHierarchyResponse *ns1__exportHierarchyResponse_) { return soap ? soap_call___ns1__exportHierarchy(soap, endpoint, NULL, ns1__exportHierarchy_, ns1__exportHierarchyResponse_) : SOAP_EOM; };
	/// Invoke 'findEntities' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__findEntities(ns1__findEntities *ns1__findEntities_, ns1__findEntitiesResponse *ns1__findEntitiesResponse_) { return soap ? soap_call___ns1__findEntities(soap, endpoint, NULL, ns1__findEntities_, ns1__findEntitiesResponse_) : SOAP_EOM; };
	/// Invoke 'getActionLogRecords' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getActionLogRecords(ns1__getActionLogRecords *ns1__getActionLogRecords_, ns1__getActionLogRecordsResponse *ns1__getActionLogRecordsResponse_) { return soap ? soap_call___ns1__getActionLogRecords(soap, endpoint, NULL, ns1__getActionLogRecords_, ns1__getActionLogRecordsResponse_) : SOAP_EOM; };
	/// Invoke 'getCollectionState' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getCollectionState(ns1__getCollectionState *ns1__getCollectionState_, ns1__getCollectionStateResponse *ns1__getCollectionStateResponse_) { return soap ? soap_call___ns1__getCollectionState(soap, endpoint, NULL, ns1__getCollectionState_, ns1__getCollectionStateResponse_) : SOAP_EOM; };
	/// Invoke 'getCustomEventData' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getCustomEventData(ns1__getCustomEventData *ns1__getCustomEventData_, ns1__getCustomEventDataResponse *ns1__getCustomEventDataResponse_) { return soap ? soap_call___ns1__getCustomEventData(soap, endpoint, NULL, ns1__getCustomEventData_, ns1__getCustomEventDataResponse_) : SOAP_EOM; };
	/// Invoke 'getEntityProperties' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getEntityProperties(ns1__getEntityProperties *ns1__getEntityProperties_, ns1__getEntityPropertiesResponse *ns1__getEntityPropertiesResponse_) { return soap ? soap_call___ns1__getEntityProperties(soap, endpoint, NULL, ns1__getEntityProperties_, ns1__getEntityPropertiesResponse_) : SOAP_EOM; };
	/// Invoke 'getEventHandler' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getEventHandler(ns1__getEventHandler *ns1__getEventHandler_, ns1__getEventHandlerResponse *ns1__getEventHandlerResponse_) { return soap ? soap_call___ns1__getEventHandler(soap, endpoint, NULL, ns1__getEventHandler_, ns1__getEventHandlerResponse_) : SOAP_EOM; };
	/// Invoke 'getEventState' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getEventState(ns1__getEventState *ns1__getEventState_, ns1__getEventStateResponse *ns1__getEventStateResponse_) { return soap ? soap_call___ns1__getEventState(soap, endpoint, NULL, ns1__getEventState_, ns1__getEventStateResponse_) : SOAP_EOM; };
	/// Invoke 'getGlobalProperty' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getGlobalProperty(ns1__getGlobalProperty *ns1__getGlobalProperty_, ns1__getGlobalPropertyResponse *ns1__getGlobalPropertyResponse_) { return soap ? soap_call___ns1__getGlobalProperty(soap, endpoint, NULL, ns1__getGlobalProperty_, ns1__getGlobalPropertyResponse_) : SOAP_EOM; };
	/// Invoke 'getMetricAggregationPeriodList' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMetricAggregationPeriodList(ns1__getMetricAggregationPeriodList *ns1__getMetricAggregationPeriodList_, ns1__getMetricAggregationPeriodListResponse *ns1__getMetricAggregationPeriodListResponse_) { return soap ? soap_call___ns1__getMetricAggregationPeriodList(soap, endpoint, NULL, ns1__getMetricAggregationPeriodList_, ns1__getMetricAggregationPeriodListResponse_) : SOAP_EOM; };
	/// Invoke 'getMetricData' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMetricData(ns1__getMetricData *ns1__getMetricData_, ns1__getMetricDataResponse *ns1__getMetricDataResponse_) { return soap ? soap_call___ns1__getMetricData(soap, endpoint, NULL, ns1__getMetricData_, ns1__getMetricDataResponse_) : SOAP_EOM; };
	/// Invoke 'getNextData' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getNextData(ns1__getNextData *ns1__getNextData_, ns1__getNextDataResponse *ns1__getNextDataResponse_) { return soap ? soap_call___ns1__getNextData(soap, endpoint, NULL, ns1__getNextData_, ns1__getNextDataResponse_) : SOAP_EOM; };
	/// Invoke 'getPolicyData' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getPolicyData(ns1__getPolicyData *ns1__getPolicyData_, ns1__getPolicyDataResponse *ns1__getPolicyDataResponse_) { return soap ? soap_call___ns1__getPolicyData(soap, endpoint, NULL, ns1__getPolicyData_, ns1__getPolicyDataResponse_) : SOAP_EOM; };
	/// Invoke 'getPolicyHistory' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getPolicyHistory(ns1__getPolicyHistory *ns1__getPolicyHistory_, ns1__getPolicyHistoryResponse *ns1__getPolicyHistoryResponse_) { return soap ? soap_call___ns1__getPolicyHistory(soap, endpoint, NULL, ns1__getPolicyHistory_, ns1__getPolicyHistoryResponse_) : SOAP_EOM; };
	/// Invoke 'getPolicyState' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getPolicyState(ns1__getPolicyState *ns1__getPolicyState_, ns1__getPolicyStateResponse *ns1__getPolicyStateResponse_) { return soap ? soap_call___ns1__getPolicyState(soap, endpoint, NULL, ns1__getPolicyState_, ns1__getPolicyStateResponse_) : SOAP_EOM; };
	/// Invoke 'getPredefinedEventTypes' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getPredefinedEventTypes(ns1__getPredefinedEventTypes *ns1__getPredefinedEventTypes_, ns1__getPredefinedEventTypesResponse *ns1__getPredefinedEventTypesResponse_) { return soap ? soap_call___ns1__getPredefinedEventTypes(soap, endpoint, NULL, ns1__getPredefinedEventTypes_, ns1__getPredefinedEventTypesResponse_) : SOAP_EOM; };
	/// Invoke 'getQueryAggregationPeriodList' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getQueryAggregationPeriodList(ns1__getQueryAggregationPeriodList *ns1__getQueryAggregationPeriodList_, ns1__getQueryAggregationPeriodListResponse *ns1__getQueryAggregationPeriodListResponse_) { return soap ? soap_call___ns1__getQueryAggregationPeriodList(soap, endpoint, NULL, ns1__getQueryAggregationPeriodList_, ns1__getQueryAggregationPeriodListResponse_) : SOAP_EOM; };
	/// Invoke 'getQueryData' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getQueryData(ns1__getQueryData *ns1__getQueryData_, ns1__getQueryDataResponse *ns1__getQueryDataResponse_) { return soap ? soap_call___ns1__getQueryData(soap, endpoint, NULL, ns1__getQueryData_, ns1__getQueryDataResponse_) : SOAP_EOM; };
	/// Invoke 'importHierarchy' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__importHierarchy(ns1__importHierarchy *ns1__importHierarchy_, ns1__importHierarchyResponse *ns1__importHierarchyResponse_) { return soap ? soap_call___ns1__importHierarchy(soap, endpoint, NULL, ns1__importHierarchy_, ns1__importHierarchyResponse_) : SOAP_EOM; };
	/// Invoke 'isPolicyActive' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__isPolicyActive(ns1__isPolicyActive *ns1__isPolicyActive_, ns1__isPolicyActiveResponse *ns1__isPolicyActiveResponse_) { return soap ? soap_call___ns1__isPolicyActive(soap, endpoint, NULL, ns1__isPolicyActive_, ns1__isPolicyActiveResponse_) : SOAP_EOM; };
	/// Invoke 'rediscoverNodeCapabilities' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__rediscoverNodeCapabilities(ns1__rediscoverNodeCapabilities *ns1__rediscoverNodeCapabilities_, ns1__rediscoverNodeCapabilitiesResponse *ns1__rediscoverNodeCapabilitiesResponse_) { return soap ? soap_call___ns1__rediscoverNodeCapabilities(soap, endpoint, NULL, ns1__rediscoverNodeCapabilities_, ns1__rediscoverNodeCapabilitiesResponse_) : SOAP_EOM; };
	/// Invoke 'removeCustomEvent' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__removeCustomEvent(ns1__removeCustomEvent *ns1__removeCustomEvent_, ns1__removeCustomEventResponse *ns1__removeCustomEventResponse_) { return soap ? soap_call___ns1__removeCustomEvent(soap, endpoint, NULL, ns1__removeCustomEvent_, ns1__removeCustomEventResponse_) : SOAP_EOM; };
	/// Invoke 'removeEntity' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__removeEntity(ns1__removeEntity *ns1__removeEntity_, ns1__removeEntityResponse *ns1__removeEntityResponse_) { return soap ? soap_call___ns1__removeEntity(soap, endpoint, NULL, ns1__removeEntity_, ns1__removeEntityResponse_) : SOAP_EOM; };
	/// Invoke 'removePolicy' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__removePolicy(ns1__removePolicy *ns1__removePolicy_, ns1__removePolicyResponse *ns1__removePolicyResponse_) { return soap ? soap_call___ns1__removePolicy(soap, endpoint, NULL, ns1__removePolicy_, ns1__removePolicyResponse_) : SOAP_EOM; };
	/// Invoke 'schedulePolicy' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__schedulePolicy(ns1__schedulePolicy *ns1__schedulePolicy_, ns1__schedulePolicyResponse *ns1__schedulePolicyResponse_) { return soap ? soap_call___ns1__schedulePolicy(soap, endpoint, NULL, ns1__schedulePolicy_, ns1__schedulePolicyResponse_) : SOAP_EOM; };
	/// Invoke 'setCollectionState' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setCollectionState(ns1__setCollectionState *ns1__setCollectionState_, ns1__setCollectionStateResponse *ns1__setCollectionStateResponse_) { return soap ? soap_call___ns1__setCollectionState(soap, endpoint, NULL, ns1__setCollectionState_, ns1__setCollectionStateResponse_) : SOAP_EOM; };
	/// Invoke 'setEntityProperties' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setEntityProperties(ns1__setEntityProperties *ns1__setEntityProperties_, ns1__setEntityPropertiesResponse *ns1__setEntityPropertiesResponse_) { return soap ? soap_call___ns1__setEntityProperties(soap, endpoint, NULL, ns1__setEntityProperties_, ns1__setEntityPropertiesResponse_) : SOAP_EOM; };
	/// Invoke 'setEventState' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setEventState(ns1__setEventState *ns1__setEventState_, ns1__setEventStateResponse *ns1__setEventStateResponse_) { return soap ? soap_call___ns1__setEventState(soap, endpoint, NULL, ns1__setEventState_, ns1__setEventStateResponse_) : SOAP_EOM; };
	/// Invoke 'setGlobalProperty' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setGlobalProperty(ns1__setGlobalProperty *ns1__setGlobalProperty_, ns1__setGlobalPropertyResponse *ns1__setGlobalPropertyResponse_) { return soap ? soap_call___ns1__setGlobalProperty(soap, endpoint, NULL, ns1__setGlobalProperty_, ns1__setGlobalPropertyResponse_) : SOAP_EOM; };
	/// Invoke 'setPolicyState' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setPolicyState(ns1__setPolicyState *ns1__setPolicyState_, ns1__setPolicyStateResponse *ns1__setPolicyStateResponse_) { return soap ? soap_call___ns1__setPolicyState(soap, endpoint, NULL, ns1__setPolicyState_, ns1__setPolicyStateResponse_) : SOAP_EOM; };
	/// Invoke 'submitSecretKey' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__submitSecretKey(ns1__submitSecretKey *ns1__submitSecretKey_, ns1__submitSecretKeyResponse *ns1__submitSecretKeyResponse_) { return soap ? soap_call___ns1__submitSecretKey(soap, endpoint, NULL, ns1__submitSecretKey_, ns1__submitSecretKeyResponse_) : SOAP_EOM; };
	/// Invoke 'subscribeEventHandler' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__subscribeEventHandler(ns1__subscribeEventHandler *ns1__subscribeEventHandler_, ns1__subscribeEventHandlerResponse *ns1__subscribeEventHandlerResponse_) { return soap ? soap_call___ns1__subscribeEventHandler(soap, endpoint, NULL, ns1__subscribeEventHandler_, ns1__subscribeEventHandlerResponse_) : SOAP_EOM; };
	/// Invoke 'subscribePredefinedEvent' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__subscribePredefinedEvent(ns1__subscribePredefinedEvent *ns1__subscribePredefinedEvent_, ns1__subscribePredefinedEventResponse *ns1__subscribePredefinedEventResponse_) { return soap ? soap_call___ns1__subscribePredefinedEvent(soap, endpoint, NULL, ns1__subscribePredefinedEvent_, ns1__subscribePredefinedEventResponse_) : SOAP_EOM; };
	/// Invoke 'unsubscribeEventHandler' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__unsubscribeEventHandler(ns1__unsubscribeEventHandler *ns1__unsubscribeEventHandler_, ns1__unsubscribeEventHandlerResponse *ns1__unsubscribeEventHandlerResponse_) { return soap ? soap_call___ns1__unsubscribeEventHandler(soap, endpoint, NULL, ns1__unsubscribeEventHandler_, ns1__unsubscribeEventHandlerResponse_) : SOAP_EOM; };
	/// Invoke 'unsubscribePredefinedEvent' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__unsubscribePredefinedEvent(ns1__unsubscribePredefinedEvent *ns1__unsubscribePredefinedEvent_, ns1__unsubscribePredefinedEventResponse *ns1__unsubscribePredefinedEventResponse_) { return soap ? soap_call___ns1__unsubscribePredefinedEvent(soap, endpoint, NULL, ns1__unsubscribePredefinedEvent_, ns1__unsubscribePredefinedEventResponse_) : SOAP_EOM; };
	/// Invoke 'updateCustomEvent' of service 'DcmPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__updateCustomEvent(ns1__updateCustomEvent *ns1__updateCustomEvent_, ns1__updateCustomEventResponse *ns1__updateCustomEventResponse_) { return soap ? soap_call___ns1__updateCustomEvent(soap, endpoint, NULL, ns1__updateCustomEvent_, ns1__updateCustomEventResponse_) : SOAP_EOM; };
};
#endif
