/* soapH.h
   Generated by gSOAP 2.7.12 from GSM.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SendNoteInfoOutIDResponse
#define SOAP_TYPE__ns1__SendNoteInfoOutIDResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SendNoteInfoOutIDResponse(struct soap*, const char*, int, const _ns1__SendNoteInfoOutIDResponse *, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoOutIDResponse * SOAP_FMAC4 soap_get__ns1__SendNoteInfoOutIDResponse(struct soap*, _ns1__SendNoteInfoOutIDResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoOutIDResponse * SOAP_FMAC4 soap_in__ns1__SendNoteInfoOutIDResponse(struct soap*, const char*, _ns1__SendNoteInfoOutIDResponse *, const char*);
SOAP_FMAC5 _ns1__SendNoteInfoOutIDResponse * SOAP_FMAC6 soap_new__ns1__SendNoteInfoOutIDResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SendNoteInfoOutIDResponse(struct soap*, _ns1__SendNoteInfoOutIDResponse*);
SOAP_FMAC3 _ns1__SendNoteInfoOutIDResponse * SOAP_FMAC4 soap_instantiate__ns1__SendNoteInfoOutIDResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SendNoteInfoOutIDResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SendNoteInfoOutID
#define SOAP_TYPE__ns1__SendNoteInfoOutID (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SendNoteInfoOutID(struct soap*, const char*, int, const _ns1__SendNoteInfoOutID *, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoOutID * SOAP_FMAC4 soap_get__ns1__SendNoteInfoOutID(struct soap*, _ns1__SendNoteInfoOutID *, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoOutID * SOAP_FMAC4 soap_in__ns1__SendNoteInfoOutID(struct soap*, const char*, _ns1__SendNoteInfoOutID *, const char*);
SOAP_FMAC5 _ns1__SendNoteInfoOutID * SOAP_FMAC6 soap_new__ns1__SendNoteInfoOutID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SendNoteInfoOutID(struct soap*, _ns1__SendNoteInfoOutID*);
SOAP_FMAC3 _ns1__SendNoteInfoOutID * SOAP_FMAC4 soap_instantiate__ns1__SendNoteInfoOutID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SendNoteInfoOutID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SendNoteInfoForUserOutIDResponse
#define SOAP_TYPE__ns1__SendNoteInfoForUserOutIDResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SendNoteInfoForUserOutIDResponse(struct soap*, const char*, int, const _ns1__SendNoteInfoForUserOutIDResponse *, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutIDResponse * SOAP_FMAC4 soap_get__ns1__SendNoteInfoForUserOutIDResponse(struct soap*, _ns1__SendNoteInfoForUserOutIDResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutIDResponse * SOAP_FMAC4 soap_in__ns1__SendNoteInfoForUserOutIDResponse(struct soap*, const char*, _ns1__SendNoteInfoForUserOutIDResponse *, const char*);
SOAP_FMAC5 _ns1__SendNoteInfoForUserOutIDResponse * SOAP_FMAC6 soap_new__ns1__SendNoteInfoForUserOutIDResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SendNoteInfoForUserOutIDResponse(struct soap*, _ns1__SendNoteInfoForUserOutIDResponse*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutIDResponse * SOAP_FMAC4 soap_instantiate__ns1__SendNoteInfoForUserOutIDResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SendNoteInfoForUserOutIDResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SendNoteInfoForUserOutID
#define SOAP_TYPE__ns1__SendNoteInfoForUserOutID (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SendNoteInfoForUserOutID(struct soap*, const char*, int, const _ns1__SendNoteInfoForUserOutID *, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutID * SOAP_FMAC4 soap_get__ns1__SendNoteInfoForUserOutID(struct soap*, _ns1__SendNoteInfoForUserOutID *, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutID * SOAP_FMAC4 soap_in__ns1__SendNoteInfoForUserOutID(struct soap*, const char*, _ns1__SendNoteInfoForUserOutID *, const char*);
SOAP_FMAC5 _ns1__SendNoteInfoForUserOutID * SOAP_FMAC6 soap_new__ns1__SendNoteInfoForUserOutID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SendNoteInfoForUserOutID(struct soap*, _ns1__SendNoteInfoForUserOutID*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutID * SOAP_FMAC4 soap_instantiate__ns1__SendNoteInfoForUserOutID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SendNoteInfoForUserOutID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SendNoteInfoResponse
#define SOAP_TYPE__ns1__SendNoteInfoResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SendNoteInfoResponse(struct soap*, const char*, int, const _ns1__SendNoteInfoResponse *, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoResponse * SOAP_FMAC4 soap_get__ns1__SendNoteInfoResponse(struct soap*, _ns1__SendNoteInfoResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoResponse * SOAP_FMAC4 soap_in__ns1__SendNoteInfoResponse(struct soap*, const char*, _ns1__SendNoteInfoResponse *, const char*);
SOAP_FMAC5 _ns1__SendNoteInfoResponse * SOAP_FMAC6 soap_new__ns1__SendNoteInfoResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SendNoteInfoResponse(struct soap*, _ns1__SendNoteInfoResponse*);
SOAP_FMAC3 _ns1__SendNoteInfoResponse * SOAP_FMAC4 soap_instantiate__ns1__SendNoteInfoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SendNoteInfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SendNoteInfo
#define SOAP_TYPE__ns1__SendNoteInfo (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SendNoteInfo(struct soap*, const char*, int, const _ns1__SendNoteInfo *, const char*);
SOAP_FMAC3 _ns1__SendNoteInfo * SOAP_FMAC4 soap_get__ns1__SendNoteInfo(struct soap*, _ns1__SendNoteInfo *, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfo * SOAP_FMAC4 soap_in__ns1__SendNoteInfo(struct soap*, const char*, _ns1__SendNoteInfo *, const char*);
SOAP_FMAC5 _ns1__SendNoteInfo * SOAP_FMAC6 soap_new__ns1__SendNoteInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SendNoteInfo(struct soap*, _ns1__SendNoteInfo*);
SOAP_FMAC3 _ns1__SendNoteInfo * SOAP_FMAC4 soap_instantiate__ns1__SendNoteInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SendNoteInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SendNoteInfoForUserResponse
#define SOAP_TYPE__ns1__SendNoteInfoForUserResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SendNoteInfoForUserResponse(struct soap*, const char*, int, const _ns1__SendNoteInfoForUserResponse *, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserResponse * SOAP_FMAC4 soap_get__ns1__SendNoteInfoForUserResponse(struct soap*, _ns1__SendNoteInfoForUserResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserResponse * SOAP_FMAC4 soap_in__ns1__SendNoteInfoForUserResponse(struct soap*, const char*, _ns1__SendNoteInfoForUserResponse *, const char*);
SOAP_FMAC5 _ns1__SendNoteInfoForUserResponse * SOAP_FMAC6 soap_new__ns1__SendNoteInfoForUserResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SendNoteInfoForUserResponse(struct soap*, _ns1__SendNoteInfoForUserResponse*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserResponse * SOAP_FMAC4 soap_instantiate__ns1__SendNoteInfoForUserResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SendNoteInfoForUserResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SendNoteInfoForUser
#define SOAP_TYPE__ns1__SendNoteInfoForUser (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SendNoteInfoForUser(struct soap*, const char*, int, const _ns1__SendNoteInfoForUser *, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUser * SOAP_FMAC4 soap_get__ns1__SendNoteInfoForUser(struct soap*, _ns1__SendNoteInfoForUser *, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUser * SOAP_FMAC4 soap_in__ns1__SendNoteInfoForUser(struct soap*, const char*, _ns1__SendNoteInfoForUser *, const char*);
SOAP_FMAC5 _ns1__SendNoteInfoForUser * SOAP_FMAC6 soap_new__ns1__SendNoteInfoForUser(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SendNoteInfoForUser(struct soap*, _ns1__SendNoteInfoForUser*);
SOAP_FMAC3 _ns1__SendNoteInfoForUser * SOAP_FMAC4 soap_instantiate__ns1__SendNoteInfoForUser(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SendNoteInfoForUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns3__SendNoteInfoOutID
#define SOAP_TYPE___ns3__SendNoteInfoOutID (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__SendNoteInfoOutID(struct soap*, struct __ns3__SendNoteInfoOutID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__SendNoteInfoOutID(struct soap*, const struct __ns3__SendNoteInfoOutID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__SendNoteInfoOutID(struct soap*, const struct __ns3__SendNoteInfoOutID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__SendNoteInfoOutID(struct soap*, const char*, int, const struct __ns3__SendNoteInfoOutID *, const char*);
SOAP_FMAC3 struct __ns3__SendNoteInfoOutID * SOAP_FMAC4 soap_get___ns3__SendNoteInfoOutID(struct soap*, struct __ns3__SendNoteInfoOutID *, const char*, const char*);
SOAP_FMAC3 struct __ns3__SendNoteInfoOutID * SOAP_FMAC4 soap_in___ns3__SendNoteInfoOutID(struct soap*, const char*, struct __ns3__SendNoteInfoOutID *, const char*);
SOAP_FMAC5 struct __ns3__SendNoteInfoOutID * SOAP_FMAC6 soap_new___ns3__SendNoteInfoOutID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__SendNoteInfoOutID(struct soap*, struct __ns3__SendNoteInfoOutID*);
SOAP_FMAC3 struct __ns3__SendNoteInfoOutID * SOAP_FMAC4 soap_instantiate___ns3__SendNoteInfoOutID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__SendNoteInfoOutID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__SendNoteInfoForUserOutID
#define SOAP_TYPE___ns3__SendNoteInfoForUserOutID (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__SendNoteInfoForUserOutID(struct soap*, struct __ns3__SendNoteInfoForUserOutID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__SendNoteInfoForUserOutID(struct soap*, const struct __ns3__SendNoteInfoForUserOutID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__SendNoteInfoForUserOutID(struct soap*, const struct __ns3__SendNoteInfoForUserOutID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__SendNoteInfoForUserOutID(struct soap*, const char*, int, const struct __ns3__SendNoteInfoForUserOutID *, const char*);
SOAP_FMAC3 struct __ns3__SendNoteInfoForUserOutID * SOAP_FMAC4 soap_get___ns3__SendNoteInfoForUserOutID(struct soap*, struct __ns3__SendNoteInfoForUserOutID *, const char*, const char*);
SOAP_FMAC3 struct __ns3__SendNoteInfoForUserOutID * SOAP_FMAC4 soap_in___ns3__SendNoteInfoForUserOutID(struct soap*, const char*, struct __ns3__SendNoteInfoForUserOutID *, const char*);
SOAP_FMAC5 struct __ns3__SendNoteInfoForUserOutID * SOAP_FMAC6 soap_new___ns3__SendNoteInfoForUserOutID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__SendNoteInfoForUserOutID(struct soap*, struct __ns3__SendNoteInfoForUserOutID*);
SOAP_FMAC3 struct __ns3__SendNoteInfoForUserOutID * SOAP_FMAC4 soap_instantiate___ns3__SendNoteInfoForUserOutID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__SendNoteInfoForUserOutID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__SendNoteInfo
#define SOAP_TYPE___ns3__SendNoteInfo (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__SendNoteInfo(struct soap*, struct __ns3__SendNoteInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__SendNoteInfo(struct soap*, const struct __ns3__SendNoteInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__SendNoteInfo(struct soap*, const struct __ns3__SendNoteInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__SendNoteInfo(struct soap*, const char*, int, const struct __ns3__SendNoteInfo *, const char*);
SOAP_FMAC3 struct __ns3__SendNoteInfo * SOAP_FMAC4 soap_get___ns3__SendNoteInfo(struct soap*, struct __ns3__SendNoteInfo *, const char*, const char*);
SOAP_FMAC3 struct __ns3__SendNoteInfo * SOAP_FMAC4 soap_in___ns3__SendNoteInfo(struct soap*, const char*, struct __ns3__SendNoteInfo *, const char*);
SOAP_FMAC5 struct __ns3__SendNoteInfo * SOAP_FMAC6 soap_new___ns3__SendNoteInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__SendNoteInfo(struct soap*, struct __ns3__SendNoteInfo*);
SOAP_FMAC3 struct __ns3__SendNoteInfo * SOAP_FMAC4 soap_instantiate___ns3__SendNoteInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__SendNoteInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__SendNoteInfoForUser
#define SOAP_TYPE___ns3__SendNoteInfoForUser (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__SendNoteInfoForUser(struct soap*, struct __ns3__SendNoteInfoForUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__SendNoteInfoForUser(struct soap*, const struct __ns3__SendNoteInfoForUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__SendNoteInfoForUser(struct soap*, const struct __ns3__SendNoteInfoForUser *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__SendNoteInfoForUser(struct soap*, const char*, int, const struct __ns3__SendNoteInfoForUser *, const char*);
SOAP_FMAC3 struct __ns3__SendNoteInfoForUser * SOAP_FMAC4 soap_get___ns3__SendNoteInfoForUser(struct soap*, struct __ns3__SendNoteInfoForUser *, const char*, const char*);
SOAP_FMAC3 struct __ns3__SendNoteInfoForUser * SOAP_FMAC4 soap_in___ns3__SendNoteInfoForUser(struct soap*, const char*, struct __ns3__SendNoteInfoForUser *, const char*);
SOAP_FMAC5 struct __ns3__SendNoteInfoForUser * SOAP_FMAC6 soap_new___ns3__SendNoteInfoForUser(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__SendNoteInfoForUser(struct soap*, struct __ns3__SendNoteInfoForUser*);
SOAP_FMAC3 struct __ns3__SendNoteInfoForUser * SOAP_FMAC4 soap_instantiate___ns3__SendNoteInfoForUser(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__SendNoteInfoForUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__SendNoteInfoOutID
#define SOAP_TYPE___ns2__SendNoteInfoOutID (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__SendNoteInfoOutID(struct soap*, struct __ns2__SendNoteInfoOutID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__SendNoteInfoOutID(struct soap*, const struct __ns2__SendNoteInfoOutID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__SendNoteInfoOutID(struct soap*, const struct __ns2__SendNoteInfoOutID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__SendNoteInfoOutID(struct soap*, const char*, int, const struct __ns2__SendNoteInfoOutID *, const char*);
SOAP_FMAC3 struct __ns2__SendNoteInfoOutID * SOAP_FMAC4 soap_get___ns2__SendNoteInfoOutID(struct soap*, struct __ns2__SendNoteInfoOutID *, const char*, const char*);
SOAP_FMAC3 struct __ns2__SendNoteInfoOutID * SOAP_FMAC4 soap_in___ns2__SendNoteInfoOutID(struct soap*, const char*, struct __ns2__SendNoteInfoOutID *, const char*);
SOAP_FMAC5 struct __ns2__SendNoteInfoOutID * SOAP_FMAC6 soap_new___ns2__SendNoteInfoOutID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns2__SendNoteInfoOutID(struct soap*, struct __ns2__SendNoteInfoOutID*);
SOAP_FMAC3 struct __ns2__SendNoteInfoOutID * SOAP_FMAC4 soap_instantiate___ns2__SendNoteInfoOutID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__SendNoteInfoOutID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__SendNoteInfoForUserOutID
#define SOAP_TYPE___ns2__SendNoteInfoForUserOutID (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__SendNoteInfoForUserOutID(struct soap*, struct __ns2__SendNoteInfoForUserOutID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__SendNoteInfoForUserOutID(struct soap*, const struct __ns2__SendNoteInfoForUserOutID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__SendNoteInfoForUserOutID(struct soap*, const struct __ns2__SendNoteInfoForUserOutID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__SendNoteInfoForUserOutID(struct soap*, const char*, int, const struct __ns2__SendNoteInfoForUserOutID *, const char*);
SOAP_FMAC3 struct __ns2__SendNoteInfoForUserOutID * SOAP_FMAC4 soap_get___ns2__SendNoteInfoForUserOutID(struct soap*, struct __ns2__SendNoteInfoForUserOutID *, const char*, const char*);
SOAP_FMAC3 struct __ns2__SendNoteInfoForUserOutID * SOAP_FMAC4 soap_in___ns2__SendNoteInfoForUserOutID(struct soap*, const char*, struct __ns2__SendNoteInfoForUserOutID *, const char*);
SOAP_FMAC5 struct __ns2__SendNoteInfoForUserOutID * SOAP_FMAC6 soap_new___ns2__SendNoteInfoForUserOutID(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns2__SendNoteInfoForUserOutID(struct soap*, struct __ns2__SendNoteInfoForUserOutID*);
SOAP_FMAC3 struct __ns2__SendNoteInfoForUserOutID * SOAP_FMAC4 soap_instantiate___ns2__SendNoteInfoForUserOutID(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__SendNoteInfoForUserOutID(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__SendNoteInfo
#define SOAP_TYPE___ns2__SendNoteInfo (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__SendNoteInfo(struct soap*, struct __ns2__SendNoteInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__SendNoteInfo(struct soap*, const struct __ns2__SendNoteInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__SendNoteInfo(struct soap*, const struct __ns2__SendNoteInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__SendNoteInfo(struct soap*, const char*, int, const struct __ns2__SendNoteInfo *, const char*);
SOAP_FMAC3 struct __ns2__SendNoteInfo * SOAP_FMAC4 soap_get___ns2__SendNoteInfo(struct soap*, struct __ns2__SendNoteInfo *, const char*, const char*);
SOAP_FMAC3 struct __ns2__SendNoteInfo * SOAP_FMAC4 soap_in___ns2__SendNoteInfo(struct soap*, const char*, struct __ns2__SendNoteInfo *, const char*);
SOAP_FMAC5 struct __ns2__SendNoteInfo * SOAP_FMAC6 soap_new___ns2__SendNoteInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns2__SendNoteInfo(struct soap*, struct __ns2__SendNoteInfo*);
SOAP_FMAC3 struct __ns2__SendNoteInfo * SOAP_FMAC4 soap_instantiate___ns2__SendNoteInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__SendNoteInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__SendNoteInfoForUser
#define SOAP_TYPE___ns2__SendNoteInfoForUser (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__SendNoteInfoForUser(struct soap*, struct __ns2__SendNoteInfoForUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__SendNoteInfoForUser(struct soap*, const struct __ns2__SendNoteInfoForUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__SendNoteInfoForUser(struct soap*, const struct __ns2__SendNoteInfoForUser *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__SendNoteInfoForUser(struct soap*, const char*, int, const struct __ns2__SendNoteInfoForUser *, const char*);
SOAP_FMAC3 struct __ns2__SendNoteInfoForUser * SOAP_FMAC4 soap_get___ns2__SendNoteInfoForUser(struct soap*, struct __ns2__SendNoteInfoForUser *, const char*, const char*);
SOAP_FMAC3 struct __ns2__SendNoteInfoForUser * SOAP_FMAC4 soap_in___ns2__SendNoteInfoForUser(struct soap*, const char*, struct __ns2__SendNoteInfoForUser *, const char*);
SOAP_FMAC5 struct __ns2__SendNoteInfoForUser * SOAP_FMAC6 soap_new___ns2__SendNoteInfoForUser(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns2__SendNoteInfoForUser(struct soap*, struct __ns2__SendNoteInfoForUser*);
SOAP_FMAC3 struct __ns2__SendNoteInfoForUser * SOAP_FMAC4 soap_instantiate___ns2__SendNoteInfoForUser(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__SendNoteInfoForUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__SendNoteInfoOutIDResponse
#define SOAP_TYPE_PointerTo_ns1__SendNoteInfoOutIDResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SendNoteInfoOutIDResponse(struct soap*, _ns1__SendNoteInfoOutIDResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SendNoteInfoOutIDResponse(struct soap*, _ns1__SendNoteInfoOutIDResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SendNoteInfoOutIDResponse(struct soap*, const char *, int, _ns1__SendNoteInfoOutIDResponse *const*, const char *);
SOAP_FMAC3 _ns1__SendNoteInfoOutIDResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__SendNoteInfoOutIDResponse(struct soap*, _ns1__SendNoteInfoOutIDResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoOutIDResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__SendNoteInfoOutIDResponse(struct soap*, const char*, _ns1__SendNoteInfoOutIDResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SendNoteInfoOutID
#define SOAP_TYPE_PointerTo_ns1__SendNoteInfoOutID (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SendNoteInfoOutID(struct soap*, _ns1__SendNoteInfoOutID *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SendNoteInfoOutID(struct soap*, _ns1__SendNoteInfoOutID *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SendNoteInfoOutID(struct soap*, const char *, int, _ns1__SendNoteInfoOutID *const*, const char *);
SOAP_FMAC3 _ns1__SendNoteInfoOutID ** SOAP_FMAC4 soap_get_PointerTo_ns1__SendNoteInfoOutID(struct soap*, _ns1__SendNoteInfoOutID **, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoOutID ** SOAP_FMAC4 soap_in_PointerTo_ns1__SendNoteInfoOutID(struct soap*, const char*, _ns1__SendNoteInfoOutID **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SendNoteInfoForUserOutIDResponse
#define SOAP_TYPE_PointerTo_ns1__SendNoteInfoForUserOutIDResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SendNoteInfoForUserOutIDResponse(struct soap*, _ns1__SendNoteInfoForUserOutIDResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SendNoteInfoForUserOutIDResponse(struct soap*, _ns1__SendNoteInfoForUserOutIDResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SendNoteInfoForUserOutIDResponse(struct soap*, const char *, int, _ns1__SendNoteInfoForUserOutIDResponse *const*, const char *);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutIDResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__SendNoteInfoForUserOutIDResponse(struct soap*, _ns1__SendNoteInfoForUserOutIDResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutIDResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__SendNoteInfoForUserOutIDResponse(struct soap*, const char*, _ns1__SendNoteInfoForUserOutIDResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SendNoteInfoForUserOutID
#define SOAP_TYPE_PointerTo_ns1__SendNoteInfoForUserOutID (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SendNoteInfoForUserOutID(struct soap*, _ns1__SendNoteInfoForUserOutID *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SendNoteInfoForUserOutID(struct soap*, _ns1__SendNoteInfoForUserOutID *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SendNoteInfoForUserOutID(struct soap*, const char *, int, _ns1__SendNoteInfoForUserOutID *const*, const char *);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutID ** SOAP_FMAC4 soap_get_PointerTo_ns1__SendNoteInfoForUserOutID(struct soap*, _ns1__SendNoteInfoForUserOutID **, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserOutID ** SOAP_FMAC4 soap_in_PointerTo_ns1__SendNoteInfoForUserOutID(struct soap*, const char*, _ns1__SendNoteInfoForUserOutID **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SendNoteInfoResponse
#define SOAP_TYPE_PointerTo_ns1__SendNoteInfoResponse (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SendNoteInfoResponse(struct soap*, _ns1__SendNoteInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SendNoteInfoResponse(struct soap*, _ns1__SendNoteInfoResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SendNoteInfoResponse(struct soap*, const char *, int, _ns1__SendNoteInfoResponse *const*, const char *);
SOAP_FMAC3 _ns1__SendNoteInfoResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__SendNoteInfoResponse(struct soap*, _ns1__SendNoteInfoResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__SendNoteInfoResponse(struct soap*, const char*, _ns1__SendNoteInfoResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SendNoteInfo
#define SOAP_TYPE_PointerTo_ns1__SendNoteInfo (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SendNoteInfo(struct soap*, _ns1__SendNoteInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SendNoteInfo(struct soap*, _ns1__SendNoteInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SendNoteInfo(struct soap*, const char *, int, _ns1__SendNoteInfo *const*, const char *);
SOAP_FMAC3 _ns1__SendNoteInfo ** SOAP_FMAC4 soap_get_PointerTo_ns1__SendNoteInfo(struct soap*, _ns1__SendNoteInfo **, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfo ** SOAP_FMAC4 soap_in_PointerTo_ns1__SendNoteInfo(struct soap*, const char*, _ns1__SendNoteInfo **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SendNoteInfoForUserResponse
#define SOAP_TYPE_PointerTo_ns1__SendNoteInfoForUserResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SendNoteInfoForUserResponse(struct soap*, _ns1__SendNoteInfoForUserResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SendNoteInfoForUserResponse(struct soap*, _ns1__SendNoteInfoForUserResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SendNoteInfoForUserResponse(struct soap*, const char *, int, _ns1__SendNoteInfoForUserResponse *const*, const char *);
SOAP_FMAC3 _ns1__SendNoteInfoForUserResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__SendNoteInfoForUserResponse(struct soap*, _ns1__SendNoteInfoForUserResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUserResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__SendNoteInfoForUserResponse(struct soap*, const char*, _ns1__SendNoteInfoForUserResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SendNoteInfoForUser
#define SOAP_TYPE_PointerTo_ns1__SendNoteInfoForUser (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SendNoteInfoForUser(struct soap*, _ns1__SendNoteInfoForUser *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SendNoteInfoForUser(struct soap*, _ns1__SendNoteInfoForUser *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SendNoteInfoForUser(struct soap*, const char *, int, _ns1__SendNoteInfoForUser *const*, const char *);
SOAP_FMAC3 _ns1__SendNoteInfoForUser ** SOAP_FMAC4 soap_get_PointerTo_ns1__SendNoteInfoForUser(struct soap*, _ns1__SendNoteInfoForUser **, const char*, const char*);
SOAP_FMAC3 _ns1__SendNoteInfoForUser ** SOAP_FMAC4 soap_in_PointerTo_ns1__SendNoteInfoForUser(struct soap*, const char*, _ns1__SendNoteInfoForUser **, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
