/* soapH.h
   Generated by gSOAP 2.7.12 from D:\program\huaWei\soap\soap\huaWei.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE__ns1__SetParameterValuesResponse_Status
#define SOAP_TYPE__ns1__SetParameterValuesResponse_Status (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__SetParameterValuesResponse_Status(struct soap*, enum _ns1__SetParameterValuesResponse_Status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__SetParameterValuesResponse_Status(struct soap*, const enum _ns1__SetParameterValuesResponse_Status *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SetParameterValuesResponse_Status(struct soap*, const char*, int, const enum _ns1__SetParameterValuesResponse_Status *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__ns1__SetParameterValuesResponse_Status2s(struct soap*, enum _ns1__SetParameterValuesResponse_Status);
SOAP_FMAC3 enum _ns1__SetParameterValuesResponse_Status * SOAP_FMAC4 soap_get__ns1__SetParameterValuesResponse_Status(struct soap*, enum _ns1__SetParameterValuesResponse_Status *, const char*, const char*);
SOAP_FMAC3 enum _ns1__SetParameterValuesResponse_Status * SOAP_FMAC4 soap_in__ns1__SetParameterValuesResponse_Status(struct soap*, const char*, enum _ns1__SetParameterValuesResponse_Status *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_ns1__SetParameterValuesResponse_Status(struct soap*, const char*, enum _ns1__SetParameterValuesResponse_Status *);

#ifndef SOAP_TYPE__ns1__ParameterAttributeStruct_Notification
#define SOAP_TYPE__ns1__ParameterAttributeStruct_Notification (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__ParameterAttributeStruct_Notification(struct soap*, enum _ns1__ParameterAttributeStruct_Notification *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__ParameterAttributeStruct_Notification(struct soap*, const enum _ns1__ParameterAttributeStruct_Notification *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ParameterAttributeStruct_Notification(struct soap*, const char*, int, const enum _ns1__ParameterAttributeStruct_Notification *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__ns1__ParameterAttributeStruct_Notification2s(struct soap*, enum _ns1__ParameterAttributeStruct_Notification);
SOAP_FMAC3 enum _ns1__ParameterAttributeStruct_Notification * SOAP_FMAC4 soap_get__ns1__ParameterAttributeStruct_Notification(struct soap*, enum _ns1__ParameterAttributeStruct_Notification *, const char*, const char*);
SOAP_FMAC3 enum _ns1__ParameterAttributeStruct_Notification * SOAP_FMAC4 soap_in__ns1__ParameterAttributeStruct_Notification(struct soap*, const char*, enum _ns1__ParameterAttributeStruct_Notification *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_ns1__ParameterAttributeStruct_Notification(struct soap*, const char*, enum _ns1__ParameterAttributeStruct_Notification *);

#ifndef SOAP_TYPE__ns1__SetParameterAttributesStruct_Notification
#define SOAP_TYPE__ns1__SetParameterAttributesStruct_Notification (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__SetParameterAttributesStruct_Notification(struct soap*, enum _ns1__SetParameterAttributesStruct_Notification *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__SetParameterAttributesStruct_Notification(struct soap*, const enum _ns1__SetParameterAttributesStruct_Notification *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SetParameterAttributesStruct_Notification(struct soap*, const char*, int, const enum _ns1__SetParameterAttributesStruct_Notification *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__ns1__SetParameterAttributesStruct_Notification2s(struct soap*, enum _ns1__SetParameterAttributesStruct_Notification);
SOAP_FMAC3 enum _ns1__SetParameterAttributesStruct_Notification * SOAP_FMAC4 soap_get__ns1__SetParameterAttributesStruct_Notification(struct soap*, enum _ns1__SetParameterAttributesStruct_Notification *, const char*, const char*);
SOAP_FMAC3 enum _ns1__SetParameterAttributesStruct_Notification * SOAP_FMAC4 soap_in__ns1__SetParameterAttributesStruct_Notification(struct soap*, const char*, enum _ns1__SetParameterAttributesStruct_Notification *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_ns1__SetParameterAttributesStruct_Notification(struct soap*, const char*, enum _ns1__SetParameterAttributesStruct_Notification *);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_ns1__ParameterKeyType
#define SOAP_TYPE_ns1__ParameterKeyType (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ParameterKeyType(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ParameterKeyType(struct soap*, std::string const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ParameterKeyType(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ParameterKeyType(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_ns1__ParameterKeyType(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_ns1__ParameterKeyType(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_ns1__ParameterKeyType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ParameterKeyType(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_ns1__ParameterKeyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ParameterKeyType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__CommandKeyType
#define SOAP_TYPE_ns1__CommandKeyType (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__CommandKeyType(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__CommandKeyType(struct soap*, std::string const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__CommandKeyType(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__CommandKeyType(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_ns1__CommandKeyType(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_ns1__CommandKeyType(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_ns1__CommandKeyType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__CommandKeyType(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_ns1__CommandKeyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__CommandKeyType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetParameterAttributesResponse
#define SOAP_TYPE__ns1__GetParameterAttributesResponse (30)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetParameterAttributesResponse(struct soap*, const char*, int, const _ns1__GetParameterAttributesResponse *, const char*);
SOAP_FMAC3 _ns1__GetParameterAttributesResponse * SOAP_FMAC4 soap_get__ns1__GetParameterAttributesResponse(struct soap*, _ns1__GetParameterAttributesResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetParameterAttributesResponse * SOAP_FMAC4 soap_in__ns1__GetParameterAttributesResponse(struct soap*, const char*, _ns1__GetParameterAttributesResponse *, const char*);
SOAP_FMAC5 _ns1__GetParameterAttributesResponse * SOAP_FMAC6 soap_new__ns1__GetParameterAttributesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetParameterAttributesResponse(struct soap*, _ns1__GetParameterAttributesResponse*);
SOAP_FMAC3 _ns1__GetParameterAttributesResponse * SOAP_FMAC4 soap_instantiate__ns1__GetParameterAttributesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetParameterAttributesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetParameterAttributes
#define SOAP_TYPE__ns1__GetParameterAttributes (29)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetParameterAttributes(struct soap*, const char*, int, const _ns1__GetParameterAttributes *, const char*);
SOAP_FMAC3 _ns1__GetParameterAttributes * SOAP_FMAC4 soap_get__ns1__GetParameterAttributes(struct soap*, _ns1__GetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 _ns1__GetParameterAttributes * SOAP_FMAC4 soap_in__ns1__GetParameterAttributes(struct soap*, const char*, _ns1__GetParameterAttributes *, const char*);
SOAP_FMAC5 _ns1__GetParameterAttributes * SOAP_FMAC6 soap_new__ns1__GetParameterAttributes(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetParameterAttributes(struct soap*, _ns1__GetParameterAttributes*);
SOAP_FMAC3 _ns1__GetParameterAttributes * SOAP_FMAC4 soap_instantiate__ns1__GetParameterAttributes(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetParameterAttributes(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SetParameterAttributesResponse
#define SOAP_TYPE__ns1__SetParameterAttributesResponse (28)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SetParameterAttributesResponse(struct soap*, const char*, int, const _ns1__SetParameterAttributesResponse *, const char*);
SOAP_FMAC3 _ns1__SetParameterAttributesResponse * SOAP_FMAC4 soap_get__ns1__SetParameterAttributesResponse(struct soap*, _ns1__SetParameterAttributesResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__SetParameterAttributesResponse * SOAP_FMAC4 soap_in__ns1__SetParameterAttributesResponse(struct soap*, const char*, _ns1__SetParameterAttributesResponse *, const char*);
SOAP_FMAC5 _ns1__SetParameterAttributesResponse * SOAP_FMAC6 soap_new__ns1__SetParameterAttributesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SetParameterAttributesResponse(struct soap*, _ns1__SetParameterAttributesResponse*);
SOAP_FMAC3 _ns1__SetParameterAttributesResponse * SOAP_FMAC4 soap_instantiate__ns1__SetParameterAttributesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SetParameterAttributesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SetParameterAttributes
#define SOAP_TYPE__ns1__SetParameterAttributes (27)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SetParameterAttributes(struct soap*, const char*, int, const _ns1__SetParameterAttributes *, const char*);
SOAP_FMAC3 _ns1__SetParameterAttributes * SOAP_FMAC4 soap_get__ns1__SetParameterAttributes(struct soap*, _ns1__SetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 _ns1__SetParameterAttributes * SOAP_FMAC4 soap_in__ns1__SetParameterAttributes(struct soap*, const char*, _ns1__SetParameterAttributes *, const char*);
SOAP_FMAC5 _ns1__SetParameterAttributes * SOAP_FMAC6 soap_new__ns1__SetParameterAttributes(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SetParameterAttributes(struct soap*, _ns1__SetParameterAttributes*);
SOAP_FMAC3 _ns1__SetParameterAttributes * SOAP_FMAC4 soap_instantiate__ns1__SetParameterAttributes(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SetParameterAttributes(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetParameterValuesResponse
#define SOAP_TYPE__ns1__GetParameterValuesResponse (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetParameterValuesResponse(struct soap*, const char*, int, const _ns1__GetParameterValuesResponse *, const char*);
SOAP_FMAC3 _ns1__GetParameterValuesResponse * SOAP_FMAC4 soap_get__ns1__GetParameterValuesResponse(struct soap*, _ns1__GetParameterValuesResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetParameterValuesResponse * SOAP_FMAC4 soap_in__ns1__GetParameterValuesResponse(struct soap*, const char*, _ns1__GetParameterValuesResponse *, const char*);
SOAP_FMAC5 _ns1__GetParameterValuesResponse * SOAP_FMAC6 soap_new__ns1__GetParameterValuesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetParameterValuesResponse(struct soap*, _ns1__GetParameterValuesResponse*);
SOAP_FMAC3 _ns1__GetParameterValuesResponse * SOAP_FMAC4 soap_instantiate__ns1__GetParameterValuesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetParameterValuesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetParameterValues
#define SOAP_TYPE__ns1__GetParameterValues (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetParameterValues(struct soap*, const char*, int, const _ns1__GetParameterValues *, const char*);
SOAP_FMAC3 _ns1__GetParameterValues * SOAP_FMAC4 soap_get__ns1__GetParameterValues(struct soap*, _ns1__GetParameterValues *, const char*, const char*);
SOAP_FMAC3 _ns1__GetParameterValues * SOAP_FMAC4 soap_in__ns1__GetParameterValues(struct soap*, const char*, _ns1__GetParameterValues *, const char*);
SOAP_FMAC5 _ns1__GetParameterValues * SOAP_FMAC6 soap_new__ns1__GetParameterValues(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetParameterValues(struct soap*, _ns1__GetParameterValues*);
SOAP_FMAC3 _ns1__GetParameterValues * SOAP_FMAC4 soap_instantiate__ns1__GetParameterValues(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetParameterValues(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SetParameterValuesResponse
#define SOAP_TYPE__ns1__SetParameterValuesResponse (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SetParameterValuesResponse(struct soap*, const char*, int, const _ns1__SetParameterValuesResponse *, const char*);
SOAP_FMAC3 _ns1__SetParameterValuesResponse * SOAP_FMAC4 soap_get__ns1__SetParameterValuesResponse(struct soap*, _ns1__SetParameterValuesResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__SetParameterValuesResponse * SOAP_FMAC4 soap_in__ns1__SetParameterValuesResponse(struct soap*, const char*, _ns1__SetParameterValuesResponse *, const char*);
SOAP_FMAC5 _ns1__SetParameterValuesResponse * SOAP_FMAC6 soap_new__ns1__SetParameterValuesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SetParameterValuesResponse(struct soap*, _ns1__SetParameterValuesResponse*);
SOAP_FMAC3 _ns1__SetParameterValuesResponse * SOAP_FMAC4 soap_instantiate__ns1__SetParameterValuesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SetParameterValuesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SetParameterValues
#define SOAP_TYPE__ns1__SetParameterValues (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SetParameterValues(struct soap*, const char*, int, const _ns1__SetParameterValues *, const char*);
SOAP_FMAC3 _ns1__SetParameterValues * SOAP_FMAC4 soap_get__ns1__SetParameterValues(struct soap*, _ns1__SetParameterValues *, const char*, const char*);
SOAP_FMAC3 _ns1__SetParameterValues * SOAP_FMAC4 soap_in__ns1__SetParameterValues(struct soap*, const char*, _ns1__SetParameterValues *, const char*);
SOAP_FMAC5 _ns1__SetParameterValues * SOAP_FMAC6 soap_new__ns1__SetParameterValues(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SetParameterValues(struct soap*, _ns1__SetParameterValues*);
SOAP_FMAC3 _ns1__SetParameterValues * SOAP_FMAC4 soap_instantiate__ns1__SetParameterValues(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SetParameterValues(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ParameterAttributeList
#define SOAP_TYPE_ParameterAttributeList (22)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterAttributeList(struct soap*, const char*, int, const ParameterAttributeList *, const char*);
SOAP_FMAC3 ParameterAttributeList * SOAP_FMAC4 soap_get_ParameterAttributeList(struct soap*, ParameterAttributeList *, const char*, const char*);
SOAP_FMAC3 ParameterAttributeList * SOAP_FMAC4 soap_in_ParameterAttributeList(struct soap*, const char*, ParameterAttributeList *, const char*);
SOAP_FMAC5 ParameterAttributeList * SOAP_FMAC6 soap_new_ParameterAttributeList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ParameterAttributeList(struct soap*, ParameterAttributeList*);
SOAP_FMAC3 ParameterAttributeList * SOAP_FMAC4 soap_instantiate_ParameterAttributeList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ParameterAttributeList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ParameterAttributeStruct
#define SOAP_TYPE_ns1__ParameterAttributeStruct (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ParameterAttributeStruct(struct soap*, const char*, int, const ns1__ParameterAttributeStruct *, const char*);
SOAP_FMAC3 ns1__ParameterAttributeStruct * SOAP_FMAC4 soap_get_ns1__ParameterAttributeStruct(struct soap*, ns1__ParameterAttributeStruct *, const char*, const char*);
SOAP_FMAC3 ns1__ParameterAttributeStruct * SOAP_FMAC4 soap_in_ns1__ParameterAttributeStruct(struct soap*, const char*, ns1__ParameterAttributeStruct *, const char*);
SOAP_FMAC5 ns1__ParameterAttributeStruct * SOAP_FMAC6 soap_new_ns1__ParameterAttributeStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ParameterAttributeStruct(struct soap*, ns1__ParameterAttributeStruct*);
SOAP_FMAC3 ns1__ParameterAttributeStruct * SOAP_FMAC4 soap_instantiate_ns1__ParameterAttributeStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ParameterAttributeStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_SetParameterAttributesList
#define SOAP_TYPE_SetParameterAttributesList (20)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SetParameterAttributesList(struct soap*, const char*, int, const SetParameterAttributesList *, const char*);
SOAP_FMAC3 SetParameterAttributesList * SOAP_FMAC4 soap_get_SetParameterAttributesList(struct soap*, SetParameterAttributesList *, const char*, const char*);
SOAP_FMAC3 SetParameterAttributesList * SOAP_FMAC4 soap_in_SetParameterAttributesList(struct soap*, const char*, SetParameterAttributesList *, const char*);
SOAP_FMAC5 SetParameterAttributesList * SOAP_FMAC6 soap_new_SetParameterAttributesList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SetParameterAttributesList(struct soap*, SetParameterAttributesList*);
SOAP_FMAC3 SetParameterAttributesList * SOAP_FMAC4 soap_instantiate_SetParameterAttributesList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SetParameterAttributesList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__SetParameterAttributesStruct
#define SOAP_TYPE_ns1__SetParameterAttributesStruct (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__SetParameterAttributesStruct(struct soap*, const char*, int, const ns1__SetParameterAttributesStruct *, const char*);
SOAP_FMAC3 ns1__SetParameterAttributesStruct * SOAP_FMAC4 soap_get_ns1__SetParameterAttributesStruct(struct soap*, ns1__SetParameterAttributesStruct *, const char*, const char*);
SOAP_FMAC3 ns1__SetParameterAttributesStruct * SOAP_FMAC4 soap_in_ns1__SetParameterAttributesStruct(struct soap*, const char*, ns1__SetParameterAttributesStruct *, const char*);
SOAP_FMAC5 ns1__SetParameterAttributesStruct * SOAP_FMAC6 soap_new_ns1__SetParameterAttributesStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__SetParameterAttributesStruct(struct soap*, ns1__SetParameterAttributesStruct*);
SOAP_FMAC3 ns1__SetParameterAttributesStruct * SOAP_FMAC4 soap_instantiate_ns1__SetParameterAttributesStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__SetParameterAttributesStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AccessList
#define SOAP_TYPE_AccessList (18)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_AccessList(struct soap*, const char*, int, const AccessList *, const char*);
SOAP_FMAC3 AccessList * SOAP_FMAC4 soap_get_AccessList(struct soap*, AccessList *, const char*, const char*);
SOAP_FMAC3 AccessList * SOAP_FMAC4 soap_in_AccessList(struct soap*, const char*, AccessList *, const char*);
SOAP_FMAC5 AccessList * SOAP_FMAC6 soap_new_AccessList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_AccessList(struct soap*, AccessList*);
SOAP_FMAC3 AccessList * SOAP_FMAC4 soap_instantiate_AccessList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_AccessList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ParameterNames
#define SOAP_TYPE_ParameterNames (17)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterNames(struct soap*, const char*, int, const ParameterNames *, const char*);
SOAP_FMAC3 ParameterNames * SOAP_FMAC4 soap_get_ParameterNames(struct soap*, ParameterNames *, const char*, const char*);
SOAP_FMAC3 ParameterNames * SOAP_FMAC4 soap_in_ParameterNames(struct soap*, const char*, ParameterNames *, const char*);
SOAP_FMAC5 ParameterNames * SOAP_FMAC6 soap_new_ParameterNames(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ParameterNames(struct soap*, ParameterNames*);
SOAP_FMAC3 ParameterNames * SOAP_FMAC4 soap_instantiate_ParameterNames(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ParameterNames(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ParameterInfoList
#define SOAP_TYPE_ParameterInfoList (16)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterInfoList(struct soap*, const char*, int, const ParameterInfoList *, const char*);
SOAP_FMAC3 ParameterInfoList * SOAP_FMAC4 soap_get_ParameterInfoList(struct soap*, ParameterInfoList *, const char*, const char*);
SOAP_FMAC3 ParameterInfoList * SOAP_FMAC4 soap_in_ParameterInfoList(struct soap*, const char*, ParameterInfoList *, const char*);
SOAP_FMAC5 ParameterInfoList * SOAP_FMAC6 soap_new_ParameterInfoList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ParameterInfoList(struct soap*, ParameterInfoList*);
SOAP_FMAC3 ParameterInfoList * SOAP_FMAC4 soap_instantiate_ParameterInfoList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ParameterInfoList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ParameterInfoStruct
#define SOAP_TYPE_ns1__ParameterInfoStruct (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ParameterInfoStruct(struct soap*, const char*, int, const ns1__ParameterInfoStruct *, const char*);
SOAP_FMAC3 ns1__ParameterInfoStruct * SOAP_FMAC4 soap_get_ns1__ParameterInfoStruct(struct soap*, ns1__ParameterInfoStruct *, const char*, const char*);
SOAP_FMAC3 ns1__ParameterInfoStruct * SOAP_FMAC4 soap_in_ns1__ParameterInfoStruct(struct soap*, const char*, ns1__ParameterInfoStruct *, const char*);
SOAP_FMAC5 ns1__ParameterInfoStruct * SOAP_FMAC6 soap_new_ns1__ParameterInfoStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ParameterInfoStruct(struct soap*, ns1__ParameterInfoStruct*);
SOAP_FMAC3 ns1__ParameterInfoStruct * SOAP_FMAC4 soap_instantiate_ns1__ParameterInfoStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ParameterInfoStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (14)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterValueList(struct soap*, const char*, int, const ParameterValueList *, const char*);
SOAP_FMAC3 ParameterValueList * SOAP_FMAC4 soap_get_ParameterValueList(struct soap*, ParameterValueList *, const char*, const char*);
SOAP_FMAC3 ParameterValueList * SOAP_FMAC4 soap_in_ParameterValueList(struct soap*, const char*, ParameterValueList *, const char*);
SOAP_FMAC5 ParameterValueList * SOAP_FMAC6 soap_new_ParameterValueList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ParameterValueList(struct soap*, ParameterValueList*);
SOAP_FMAC3 ParameterValueList * SOAP_FMAC4 soap_instantiate_ParameterValueList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ParameterValueList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ParameterValueStruct
#define SOAP_TYPE_ns1__ParameterValueStruct (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ParameterValueStruct(struct soap*, const char*, int, const ns1__ParameterValueStruct *, const char*);
SOAP_FMAC3 ns1__ParameterValueStruct * SOAP_FMAC4 soap_get_ns1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct *, const char*, const char*);
SOAP_FMAC3 ns1__ParameterValueStruct * SOAP_FMAC4 soap_in_ns1__ParameterValueStruct(struct soap*, const char*, ns1__ParameterValueStruct *, const char*);
SOAP_FMAC5 ns1__ParameterValueStruct * SOAP_FMAC6 soap_new_ns1__ParameterValueStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct*);
SOAP_FMAC3 ns1__ParameterValueStruct * SOAP_FMAC4 soap_instantiate_ns1__ParameterValueStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ParameterValueStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EventList
#define SOAP_TYPE_EventList (12)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EventList(struct soap*, const char*, int, const EventList *, const char*);
SOAP_FMAC3 EventList * SOAP_FMAC4 soap_get_EventList(struct soap*, EventList *, const char*, const char*);
SOAP_FMAC3 EventList * SOAP_FMAC4 soap_in_EventList(struct soap*, const char*, EventList *, const char*);
SOAP_FMAC5 EventList * SOAP_FMAC6 soap_new_EventList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EventList(struct soap*, EventList*);
SOAP_FMAC3 EventList * SOAP_FMAC4 soap_instantiate_EventList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EventList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__EventStruct
#define SOAP_TYPE_ns1__EventStruct (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__EventStruct(struct soap*, const char*, int, const ns1__EventStruct *, const char*);
SOAP_FMAC3 ns1__EventStruct * SOAP_FMAC4 soap_get_ns1__EventStruct(struct soap*, ns1__EventStruct *, const char*, const char*);
SOAP_FMAC3 ns1__EventStruct * SOAP_FMAC4 soap_in_ns1__EventStruct(struct soap*, const char*, ns1__EventStruct *, const char*);
SOAP_FMAC5 ns1__EventStruct * SOAP_FMAC6 soap_new_ns1__EventStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__EventStruct(struct soap*, ns1__EventStruct*);
SOAP_FMAC3 ns1__EventStruct * SOAP_FMAC4 soap_instantiate_ns1__EventStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__EventStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__DeviceIdStruct
#define SOAP_TYPE_ns1__DeviceIdStruct (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DeviceIdStruct(struct soap*, const char*, int, const ns1__DeviceIdStruct *, const char*);
SOAP_FMAC3 ns1__DeviceIdStruct * SOAP_FMAC4 soap_get_ns1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct *, const char*, const char*);
SOAP_FMAC3 ns1__DeviceIdStruct * SOAP_FMAC4 soap_in_ns1__DeviceIdStruct(struct soap*, const char*, ns1__DeviceIdStruct *, const char*);
SOAP_FMAC5 ns1__DeviceIdStruct * SOAP_FMAC6 soap_new_ns1__DeviceIdStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct*);
SOAP_FMAC3 ns1__DeviceIdStruct * SOAP_FMAC4 soap_instantiate_ns1__DeviceIdStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__DeviceIdStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anySimpleType(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anySimpleType(struct soap*, std::string const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anySimpleType(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anySimpleType(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__anySimpleType(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__anySimpleType(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_xsd__anySimpleType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anySimpleType(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_xsd__anySimpleType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anySimpleType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__GetParameterAttributes
#define SOAP_TYPE___ns1__GetParameterAttributes (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetParameterAttributes(struct soap*, struct __ns1__GetParameterAttributes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetParameterAttributes(struct soap*, const struct __ns1__GetParameterAttributes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetParameterAttributes(struct soap*, const struct __ns1__GetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetParameterAttributes(struct soap*, const char*, int, const struct __ns1__GetParameterAttributes *, const char*);
SOAP_FMAC3 struct __ns1__GetParameterAttributes * SOAP_FMAC4 soap_get___ns1__GetParameterAttributes(struct soap*, struct __ns1__GetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetParameterAttributes * SOAP_FMAC4 soap_in___ns1__GetParameterAttributes(struct soap*, const char*, struct __ns1__GetParameterAttributes *, const char*);
SOAP_FMAC5 struct __ns1__GetParameterAttributes * SOAP_FMAC6 soap_new___ns1__GetParameterAttributes(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__GetParameterAttributes(struct soap*, struct __ns1__GetParameterAttributes*);
SOAP_FMAC3 struct __ns1__GetParameterAttributes * SOAP_FMAC4 soap_instantiate___ns1__GetParameterAttributes(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetParameterAttributes(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__SetParameterAttributes
#define SOAP_TYPE___ns1__SetParameterAttributes (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__SetParameterAttributes(struct soap*, struct __ns1__SetParameterAttributes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__SetParameterAttributes(struct soap*, const struct __ns1__SetParameterAttributes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__SetParameterAttributes(struct soap*, const struct __ns1__SetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__SetParameterAttributes(struct soap*, const char*, int, const struct __ns1__SetParameterAttributes *, const char*);
SOAP_FMAC3 struct __ns1__SetParameterAttributes * SOAP_FMAC4 soap_get___ns1__SetParameterAttributes(struct soap*, struct __ns1__SetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 struct __ns1__SetParameterAttributes * SOAP_FMAC4 soap_in___ns1__SetParameterAttributes(struct soap*, const char*, struct __ns1__SetParameterAttributes *, const char*);
SOAP_FMAC5 struct __ns1__SetParameterAttributes * SOAP_FMAC6 soap_new___ns1__SetParameterAttributes(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__SetParameterAttributes(struct soap*, struct __ns1__SetParameterAttributes*);
SOAP_FMAC3 struct __ns1__SetParameterAttributes * SOAP_FMAC4 soap_instantiate___ns1__SetParameterAttributes(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__SetParameterAttributes(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetParameterValues
#define SOAP_TYPE___ns1__GetParameterValues (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetParameterValues(struct soap*, struct __ns1__GetParameterValues *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetParameterValues(struct soap*, const struct __ns1__GetParameterValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetParameterValues(struct soap*, const struct __ns1__GetParameterValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetParameterValues(struct soap*, const char*, int, const struct __ns1__GetParameterValues *, const char*);
SOAP_FMAC3 struct __ns1__GetParameterValues * SOAP_FMAC4 soap_get___ns1__GetParameterValues(struct soap*, struct __ns1__GetParameterValues *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetParameterValues * SOAP_FMAC4 soap_in___ns1__GetParameterValues(struct soap*, const char*, struct __ns1__GetParameterValues *, const char*);
SOAP_FMAC5 struct __ns1__GetParameterValues * SOAP_FMAC6 soap_new___ns1__GetParameterValues(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__GetParameterValues(struct soap*, struct __ns1__GetParameterValues*);
SOAP_FMAC3 struct __ns1__GetParameterValues * SOAP_FMAC4 soap_instantiate___ns1__GetParameterValues(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetParameterValues(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__SetParameterValues
#define SOAP_TYPE___ns1__SetParameterValues (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__SetParameterValues(struct soap*, struct __ns1__SetParameterValues *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__SetParameterValues(struct soap*, const struct __ns1__SetParameterValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__SetParameterValues(struct soap*, const struct __ns1__SetParameterValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__SetParameterValues(struct soap*, const char*, int, const struct __ns1__SetParameterValues *, const char*);
SOAP_FMAC3 struct __ns1__SetParameterValues * SOAP_FMAC4 soap_get___ns1__SetParameterValues(struct soap*, struct __ns1__SetParameterValues *, const char*, const char*);
SOAP_FMAC3 struct __ns1__SetParameterValues * SOAP_FMAC4 soap_in___ns1__SetParameterValues(struct soap*, const char*, struct __ns1__SetParameterValues *, const char*);
SOAP_FMAC5 struct __ns1__SetParameterValues * SOAP_FMAC6 soap_new___ns1__SetParameterValues(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__SetParameterValues(struct soap*, struct __ns1__SetParameterValues*);
SOAP_FMAC3 struct __ns1__SetParameterValues * SOAP_FMAC4 soap_instantiate___ns1__SetParameterValues(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__SetParameterValues(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__GetParameterAttributesResponse
#define SOAP_TYPE_PointerTo_ns1__GetParameterAttributesResponse (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetParameterAttributesResponse(struct soap*, _ns1__GetParameterAttributesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetParameterAttributesResponse(struct soap*, _ns1__GetParameterAttributesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetParameterAttributesResponse(struct soap*, const char *, int, _ns1__GetParameterAttributesResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetParameterAttributesResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetParameterAttributesResponse(struct soap*, _ns1__GetParameterAttributesResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetParameterAttributesResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetParameterAttributesResponse(struct soap*, const char*, _ns1__GetParameterAttributesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetParameterAttributes
#define SOAP_TYPE_PointerTo_ns1__GetParameterAttributes (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetParameterAttributes(struct soap*, _ns1__GetParameterAttributes *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetParameterAttributes(struct soap*, _ns1__GetParameterAttributes *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetParameterAttributes(struct soap*, const char *, int, _ns1__GetParameterAttributes *const*, const char *);
SOAP_FMAC3 _ns1__GetParameterAttributes ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetParameterAttributes(struct soap*, _ns1__GetParameterAttributes **, const char*, const char*);
SOAP_FMAC3 _ns1__GetParameterAttributes ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetParameterAttributes(struct soap*, const char*, _ns1__GetParameterAttributes **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SetParameterAttributesResponse
#define SOAP_TYPE_PointerTo_ns1__SetParameterAttributesResponse (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SetParameterAttributesResponse(struct soap*, _ns1__SetParameterAttributesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SetParameterAttributesResponse(struct soap*, _ns1__SetParameterAttributesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SetParameterAttributesResponse(struct soap*, const char *, int, _ns1__SetParameterAttributesResponse *const*, const char *);
SOAP_FMAC3 _ns1__SetParameterAttributesResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__SetParameterAttributesResponse(struct soap*, _ns1__SetParameterAttributesResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__SetParameterAttributesResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__SetParameterAttributesResponse(struct soap*, const char*, _ns1__SetParameterAttributesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SetParameterAttributes
#define SOAP_TYPE_PointerTo_ns1__SetParameterAttributes (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SetParameterAttributes(struct soap*, _ns1__SetParameterAttributes *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SetParameterAttributes(struct soap*, _ns1__SetParameterAttributes *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SetParameterAttributes(struct soap*, const char *, int, _ns1__SetParameterAttributes *const*, const char *);
SOAP_FMAC3 _ns1__SetParameterAttributes ** SOAP_FMAC4 soap_get_PointerTo_ns1__SetParameterAttributes(struct soap*, _ns1__SetParameterAttributes **, const char*, const char*);
SOAP_FMAC3 _ns1__SetParameterAttributes ** SOAP_FMAC4 soap_in_PointerTo_ns1__SetParameterAttributes(struct soap*, const char*, _ns1__SetParameterAttributes **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetParameterValuesResponse
#define SOAP_TYPE_PointerTo_ns1__GetParameterValuesResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetParameterValuesResponse(struct soap*, _ns1__GetParameterValuesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetParameterValuesResponse(struct soap*, _ns1__GetParameterValuesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetParameterValuesResponse(struct soap*, const char *, int, _ns1__GetParameterValuesResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetParameterValuesResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetParameterValuesResponse(struct soap*, _ns1__GetParameterValuesResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetParameterValuesResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetParameterValuesResponse(struct soap*, const char*, _ns1__GetParameterValuesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetParameterValues
#define SOAP_TYPE_PointerTo_ns1__GetParameterValues (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetParameterValues(struct soap*, _ns1__GetParameterValues *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetParameterValues(struct soap*, _ns1__GetParameterValues *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetParameterValues(struct soap*, const char *, int, _ns1__GetParameterValues *const*, const char *);
SOAP_FMAC3 _ns1__GetParameterValues ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetParameterValues(struct soap*, _ns1__GetParameterValues **, const char*, const char*);
SOAP_FMAC3 _ns1__GetParameterValues ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetParameterValues(struct soap*, const char*, _ns1__GetParameterValues **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SetParameterValuesResponse
#define SOAP_TYPE_PointerTo_ns1__SetParameterValuesResponse (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SetParameterValuesResponse(struct soap*, _ns1__SetParameterValuesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SetParameterValuesResponse(struct soap*, _ns1__SetParameterValuesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SetParameterValuesResponse(struct soap*, const char *, int, _ns1__SetParameterValuesResponse *const*, const char *);
SOAP_FMAC3 _ns1__SetParameterValuesResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__SetParameterValuesResponse(struct soap*, _ns1__SetParameterValuesResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__SetParameterValuesResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__SetParameterValuesResponse(struct soap*, const char*, _ns1__SetParameterValuesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SetParameterValues
#define SOAP_TYPE_PointerTo_ns1__SetParameterValues (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SetParameterValues(struct soap*, _ns1__SetParameterValues *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SetParameterValues(struct soap*, _ns1__SetParameterValues *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SetParameterValues(struct soap*, const char *, int, _ns1__SetParameterValues *const*, const char *);
SOAP_FMAC3 _ns1__SetParameterValues ** SOAP_FMAC4 soap_get_PointerTo_ns1__SetParameterValues(struct soap*, _ns1__SetParameterValues **, const char*, const char*);
SOAP_FMAC3 _ns1__SetParameterValues ** SOAP_FMAC4 soap_in_PointerTo_ns1__SetParameterValues(struct soap*, const char*, _ns1__SetParameterValues **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__ParameterAttributeStruct
#define SOAP_TYPE_PointerToPointerTons1__ParameterAttributeStruct (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__ParameterAttributeStruct(struct soap*, ns1__ParameterAttributeStruct **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__ParameterAttributeStruct(struct soap*, ns1__ParameterAttributeStruct **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__ParameterAttributeStruct(struct soap*, const char *, int, ns1__ParameterAttributeStruct **const*, const char *);
SOAP_FMAC3 ns1__ParameterAttributeStruct *** SOAP_FMAC4 soap_get_PointerToPointerTons1__ParameterAttributeStruct(struct soap*, ns1__ParameterAttributeStruct ***, const char*, const char*);
SOAP_FMAC3 ns1__ParameterAttributeStruct *** SOAP_FMAC4 soap_in_PointerToPointerTons1__ParameterAttributeStruct(struct soap*, const char*, ns1__ParameterAttributeStruct ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__ParameterAttributeStruct
#define SOAP_TYPE_PointerTons1__ParameterAttributeStruct (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ParameterAttributeStruct(struct soap*, ns1__ParameterAttributeStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ParameterAttributeStruct(struct soap*, ns1__ParameterAttributeStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ParameterAttributeStruct(struct soap*, const char *, int, ns1__ParameterAttributeStruct *const*, const char *);
SOAP_FMAC3 ns1__ParameterAttributeStruct ** SOAP_FMAC4 soap_get_PointerTons1__ParameterAttributeStruct(struct soap*, ns1__ParameterAttributeStruct **, const char*, const char*);
SOAP_FMAC3 ns1__ParameterAttributeStruct ** SOAP_FMAC4 soap_in_PointerTons1__ParameterAttributeStruct(struct soap*, const char*, ns1__ParameterAttributeStruct **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__SetParameterAttributesStruct
#define SOAP_TYPE_PointerToPointerTons1__SetParameterAttributesStruct (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__SetParameterAttributesStruct(struct soap*, ns1__SetParameterAttributesStruct **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__SetParameterAttributesStruct(struct soap*, ns1__SetParameterAttributesStruct **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__SetParameterAttributesStruct(struct soap*, const char *, int, ns1__SetParameterAttributesStruct **const*, const char *);
SOAP_FMAC3 ns1__SetParameterAttributesStruct *** SOAP_FMAC4 soap_get_PointerToPointerTons1__SetParameterAttributesStruct(struct soap*, ns1__SetParameterAttributesStruct ***, const char*, const char*);
SOAP_FMAC3 ns1__SetParameterAttributesStruct *** SOAP_FMAC4 soap_in_PointerToPointerTons1__SetParameterAttributesStruct(struct soap*, const char*, ns1__SetParameterAttributesStruct ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__SetParameterAttributesStruct
#define SOAP_TYPE_PointerTons1__SetParameterAttributesStruct (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__SetParameterAttributesStruct(struct soap*, ns1__SetParameterAttributesStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__SetParameterAttributesStruct(struct soap*, ns1__SetParameterAttributesStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__SetParameterAttributesStruct(struct soap*, const char *, int, ns1__SetParameterAttributesStruct *const*, const char *);
SOAP_FMAC3 ns1__SetParameterAttributesStruct ** SOAP_FMAC4 soap_get_PointerTons1__SetParameterAttributesStruct(struct soap*, ns1__SetParameterAttributesStruct **, const char*, const char*);
SOAP_FMAC3 ns1__SetParameterAttributesStruct ** SOAP_FMAC4 soap_in_PointerTons1__SetParameterAttributesStruct(struct soap*, const char*, ns1__SetParameterAttributesStruct **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__ParameterInfoStruct
#define SOAP_TYPE_PointerToPointerTons1__ParameterInfoStruct (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__ParameterInfoStruct(struct soap*, ns1__ParameterInfoStruct **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__ParameterInfoStruct(struct soap*, ns1__ParameterInfoStruct **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__ParameterInfoStruct(struct soap*, const char *, int, ns1__ParameterInfoStruct **const*, const char *);
SOAP_FMAC3 ns1__ParameterInfoStruct *** SOAP_FMAC4 soap_get_PointerToPointerTons1__ParameterInfoStruct(struct soap*, ns1__ParameterInfoStruct ***, const char*, const char*);
SOAP_FMAC3 ns1__ParameterInfoStruct *** SOAP_FMAC4 soap_in_PointerToPointerTons1__ParameterInfoStruct(struct soap*, const char*, ns1__ParameterInfoStruct ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__ParameterInfoStruct
#define SOAP_TYPE_PointerTons1__ParameterInfoStruct (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ParameterInfoStruct(struct soap*, ns1__ParameterInfoStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ParameterInfoStruct(struct soap*, ns1__ParameterInfoStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ParameterInfoStruct(struct soap*, const char *, int, ns1__ParameterInfoStruct *const*, const char *);
SOAP_FMAC3 ns1__ParameterInfoStruct ** SOAP_FMAC4 soap_get_PointerTons1__ParameterInfoStruct(struct soap*, ns1__ParameterInfoStruct **, const char*, const char*);
SOAP_FMAC3 ns1__ParameterInfoStruct ** SOAP_FMAC4 soap_in_PointerTons1__ParameterInfoStruct(struct soap*, const char*, ns1__ParameterInfoStruct **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__ParameterValueStruct
#define SOAP_TYPE_PointerToPointerTons1__ParameterValueStruct (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__ParameterValueStruct(struct soap*, const char *, int, ns1__ParameterValueStruct **const*, const char *);
SOAP_FMAC3 ns1__ParameterValueStruct *** SOAP_FMAC4 soap_get_PointerToPointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct ***, const char*, const char*);
SOAP_FMAC3 ns1__ParameterValueStruct *** SOAP_FMAC4 soap_in_PointerToPointerTons1__ParameterValueStruct(struct soap*, const char*, ns1__ParameterValueStruct ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__ParameterValueStruct
#define SOAP_TYPE_PointerTons1__ParameterValueStruct (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ParameterValueStruct(struct soap*, const char *, int, ns1__ParameterValueStruct *const*, const char *);
SOAP_FMAC3 ns1__ParameterValueStruct ** SOAP_FMAC4 soap_get_PointerTons1__ParameterValueStruct(struct soap*, ns1__ParameterValueStruct **, const char*, const char*);
SOAP_FMAC3 ns1__ParameterValueStruct ** SOAP_FMAC4 soap_in_PointerTons1__ParameterValueStruct(struct soap*, const char*, ns1__ParameterValueStruct **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__EventStruct
#define SOAP_TYPE_PointerToPointerTons1__EventStruct (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__EventStruct(struct soap*, ns1__EventStruct **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__EventStruct(struct soap*, ns1__EventStruct **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__EventStruct(struct soap*, const char *, int, ns1__EventStruct **const*, const char *);
SOAP_FMAC3 ns1__EventStruct *** SOAP_FMAC4 soap_get_PointerToPointerTons1__EventStruct(struct soap*, ns1__EventStruct ***, const char*, const char*);
SOAP_FMAC3 ns1__EventStruct *** SOAP_FMAC4 soap_in_PointerToPointerTons1__EventStruct(struct soap*, const char*, ns1__EventStruct ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__EventStruct
#define SOAP_TYPE_PointerTons1__EventStruct (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__EventStruct(struct soap*, ns1__EventStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__EventStruct(struct soap*, ns1__EventStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__EventStruct(struct soap*, const char *, int, ns1__EventStruct *const*, const char *);
SOAP_FMAC3 ns1__EventStruct ** SOAP_FMAC4 soap_get_PointerTons1__EventStruct(struct soap*, ns1__EventStruct **, const char*, const char*);
SOAP_FMAC3 ns1__EventStruct ** SOAP_FMAC4 soap_in_PointerTons1__EventStruct(struct soap*, const char*, ns1__EventStruct **, const char*);

#ifndef SOAP_TYPE_PointerToParameterAttributeList
#define SOAP_TYPE_PointerToParameterAttributeList (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterAttributeList(struct soap*, ParameterAttributeList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterAttributeList(struct soap*, ParameterAttributeList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterAttributeList(struct soap*, const char *, int, ParameterAttributeList *const*, const char *);
SOAP_FMAC3 ParameterAttributeList ** SOAP_FMAC4 soap_get_PointerToParameterAttributeList(struct soap*, ParameterAttributeList **, const char*, const char*);
SOAP_FMAC3 ParameterAttributeList ** SOAP_FMAC4 soap_in_PointerToParameterAttributeList(struct soap*, const char*, ParameterAttributeList **, const char*);

#ifndef SOAP_TYPE_PointerToSetParameterAttributesList
#define SOAP_TYPE_PointerToSetParameterAttributesList (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSetParameterAttributesList(struct soap*, SetParameterAttributesList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSetParameterAttributesList(struct soap*, SetParameterAttributesList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSetParameterAttributesList(struct soap*, const char *, int, SetParameterAttributesList *const*, const char *);
SOAP_FMAC3 SetParameterAttributesList ** SOAP_FMAC4 soap_get_PointerToSetParameterAttributesList(struct soap*, SetParameterAttributesList **, const char*, const char*);
SOAP_FMAC3 SetParameterAttributesList ** SOAP_FMAC4 soap_in_PointerToSetParameterAttributesList(struct soap*, const char*, SetParameterAttributesList **, const char*);

#ifndef SOAP_TYPE_PointerToParameterNames
#define SOAP_TYPE_PointerToParameterNames (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterNames(struct soap*, ParameterNames *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterNames(struct soap*, ParameterNames *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterNames(struct soap*, const char *, int, ParameterNames *const*, const char *);
SOAP_FMAC3 ParameterNames ** SOAP_FMAC4 soap_get_PointerToParameterNames(struct soap*, ParameterNames **, const char*, const char*);
SOAP_FMAC3 ParameterNames ** SOAP_FMAC4 soap_in_PointerToParameterNames(struct soap*, const char*, ParameterNames **, const char*);

#ifndef SOAP_TYPE_PointerToParameterValueList
#define SOAP_TYPE_PointerToParameterValueList (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterValueList(struct soap*, ParameterValueList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterValueList(struct soap*, ParameterValueList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterValueList(struct soap*, const char *, int, ParameterValueList *const*, const char *);
SOAP_FMAC3 ParameterValueList ** SOAP_FMAC4 soap_get_PointerToParameterValueList(struct soap*, ParameterValueList **, const char*, const char*);
SOAP_FMAC3 ParameterValueList ** SOAP_FMAC4 soap_in_PointerToParameterValueList(struct soap*, const char*, ParameterValueList **, const char*);

#ifndef SOAP_TYPE_PointerTons1__DeviceIdStruct
#define SOAP_TYPE_PointerTons1__DeviceIdStruct (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DeviceIdStruct(struct soap*, const char *, int, ns1__DeviceIdStruct *const*, const char *);
SOAP_FMAC3 ns1__DeviceIdStruct ** SOAP_FMAC4 soap_get_PointerTons1__DeviceIdStruct(struct soap*, ns1__DeviceIdStruct **, const char*, const char*);
SOAP_FMAC3 ns1__DeviceIdStruct ** SOAP_FMAC4 soap_in_PointerTons1__DeviceIdStruct(struct soap*, const char*, ns1__DeviceIdStruct **, const char*);

#ifndef SOAP_TYPE_PointerToAccessList
#define SOAP_TYPE_PointerToAccessList (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToAccessList(struct soap*, AccessList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToAccessList(struct soap*, AccessList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToAccessList(struct soap*, const char *, int, AccessList *const*, const char *);
SOAP_FMAC3 AccessList ** SOAP_FMAC4 soap_get_PointerToAccessList(struct soap*, AccessList **, const char*, const char*);
SOAP_FMAC3 AccessList ** SOAP_FMAC4 soap_in_PointerToAccessList(struct soap*, const char*, AccessList **, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
