/* soapcwmpProxy.h
   Generated by gSOAP 2.7.12 from huaWei.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapcwmpProxy_H
#define soapcwmpProxy_H
#include "soapH.h"
class cwmp
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'cwmp' (change as needed)
	char szUrl[32];//±£´æurl
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	cwmp()
	{ soap = soap_new(); endpoint = "http://localhost:8080/cwmp"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"cwmp", "urn:dslforum-org:cwmp-1-1", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	cwmp( char* pszServerIP, char* pszServerPort )
	{ 
		soap = soap_new(); 

		if( (pszServerIP!=NULL) && (pszServerPort!=NULL) )
		{			
			sprintf( szUrl, "http://%s:%s/cwmp", pszServerIP, pszServerPort );
			endpoint = szUrl;
		}
		else
		{
            endpoint = "http://localhost:8080/cwmp"; 
		}

		if(soap && !soap->namespaces) 
		{ 
			static const struct Namespace namespaces[] = 
			{
				{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
				{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
				{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
				{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
				{"cwmp", "urn:dslforum-org:cwmp-1-1", NULL, NULL},
				{NULL, NULL, NULL, NULL}
            };
            
			soap->namespaces = namespaces;
		} 
	};
	/// Destructor frees deserialized data and soap engine context
	virtual ~cwmp() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'XFileEvent' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__XFileEvent(_cwmp__XFileEvent *cwmp__XFileEvent, _cwmp__XFileEventResponse *cwmp__XFileEventResponse) { return soap ? soap_call___cwmp__XFileEvent(soap, endpoint, NULL, cwmp__XFileEvent, cwmp__XFileEventResponse) : SOAP_EOM; };
	/// Invoke 'Boot' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__Boot(_cwmp__Boot *cwmp__Boot, _cwmp__BootResponse *cwmp__BootResponse) { return soap ? soap_call___cwmp__Boot(soap, endpoint, NULL, cwmp__Boot, cwmp__BootResponse) : SOAP_EOM; };
	/// Invoke 'ValueChange' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__ValueChange(_cwmp__ValueChange *cwmp__ValueChange, _cwmp__ValueChangeResponse *cwmp__ValueChangeResponse) { return soap ? soap_call___cwmp__ValueChange(soap, endpoint, NULL, cwmp__ValueChange, cwmp__ValueChangeResponse) : SOAP_EOM; };
	/// Invoke 'Periodic' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__Periodic(_cwmp__Periodic *cwmp__Periodic, _cwmp__PeriodicResponse *cwmp__PeriodicResponse) { return soap ? soap_call___cwmp__Periodic(soap, endpoint, NULL, cwmp__Periodic, cwmp__PeriodicResponse) : SOAP_EOM; };
	/// Invoke 'CpeTransferComplete' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__CpeTransferComplete(_cwmp__CpeTransferComplete *cwmp__CpeTransferComplete, _cwmp__CpeTransferCompleteResponse *cwmp__CpeTransferCompleteResponse) { return soap ? soap_call___cwmp__CpeTransferComplete(soap, endpoint, NULL, cwmp__CpeTransferComplete, cwmp__CpeTransferCompleteResponse) : SOAP_EOM; };
	/// Invoke 'Download' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__Download(_cwmp__Download *cwmp__Download, _cwmp__DownloadResponse *cwmp__DownloadResponse) { return soap ? soap_call___cwmp__Download(soap, endpoint, NULL, cwmp__Download, cwmp__DownloadResponse) : SOAP_EOM; };
	/// Invoke 'SetParameterValues' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__SetParameterValues(_cwmp__SetParameterValues *cwmp__SetParameterValues, _cwmp__SetParameterValuesResponse *cwmp__SetParameterValuesResponse) { return soap ? soap_call___cwmp__SetParameterValues(soap, endpoint, NULL, cwmp__SetParameterValues, cwmp__SetParameterValuesResponse) : SOAP_EOM; };
	/// Invoke 'GetParameterValues' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__GetParameterValues(_cwmp__GetParameterValues *cwmp__GetParameterValues, _cwmp__GetParameterValuesResponse *cwmp__GetParameterValuesResponse) { return soap ? soap_call___cwmp__GetParameterValues(soap, endpoint, NULL, cwmp__GetParameterValues, cwmp__GetParameterValuesResponse) : SOAP_EOM; };
	/// Invoke 'SetParameterAttributes' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__SetParameterAttributes(_cwmp__SetParameterAttributes *cwmp__SetParameterAttributes, _cwmp__SetParameterAttributesResponse *cwmp__SetParameterAttributesResponse) { return soap ? soap_call___cwmp__SetParameterAttributes(soap, endpoint, NULL, cwmp__SetParameterAttributes, cwmp__SetParameterAttributesResponse) : SOAP_EOM; };
	/// Invoke 'GetParameterAttributes' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__GetParameterAttributes(_cwmp__GetParameterAttributes *cwmp__GetParameterAttributes, _cwmp__GetParameterAttributesResponse *cwmp__GetParameterAttributesResponse) { return soap ? soap_call___cwmp__GetParameterAttributes(soap, endpoint, NULL, cwmp__GetParameterAttributes, cwmp__GetParameterAttributesResponse) : SOAP_EOM; };
	/// Invoke 'Reboot' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__Reboot(_cwmp__Reboot *cwmp__Reboot, _cwmp__RebootResponse *cwmp__RebootResponse) { return soap ? soap_call___cwmp__Reboot(soap, endpoint, NULL, cwmp__Reboot, cwmp__RebootResponse) : SOAP_EOM; };
	/// Invoke 'FactoryReset' of service 'cwmp' and return error code (or SOAP_OK)
	virtual int __cwmp__FactoryReset(_cwmp__FactoryReset *cwmp__FactoryReset, _cwmp__FactoryResetResponse *cwmp__FactoryResetResponse) { return soap ? soap_call___cwmp__FactoryReset(soap, endpoint, NULL, cwmp__FactoryReset, cwmp__FactoryResetResponse) : SOAP_EOM; };
};
#endif
